import sys
import io
import json
import math
import os
import contextlib
import warnings
from collections import Counter

import pandas as pd
import yfinance as yf
from tqdm import tqdm

# Phase B: yfinance fundamental catalysts (earnings, short, analyst)
try:
    from apex_catalysts import (
        get_catalyst_data,
        derive_catalyst_signals,
        score_delta_for_catalyst_signals,
    )
    CATALYSTS_AVAILABLE = True
except ImportError:
    CATALYSTS_AVAILABLE = False

# =============================================================
# SETTINGS
# =============================================================
US_TICKER_FILE  = "us_tickers.txt"
EU_TICKER_FILE  = "eu_tickers.txt"       # create this file with EU tickers
SECTOR_CACHE    = "sector_cache.json"
SIGNAL_MEMORY   = "signal_memory.json"    # local persistent — independent of git pull

TOP_RESULTS     = 20
BATCH_SIZE      = 80
HISTORY_PERIOD  = "18mo"

MIN_DATA_DAYS       = 100
MIN_PRICE           = 2
MIN_AVG_VOLUME      = 50_000
MIN_DOLLAR_VOLUME   = 500_000

# Adaptive relaxation: if fewer than MIN_SIGNALS pass, thresholds loosen
MIN_SIGNALS         = 1
MAX_SIGNALS         = 10
DUPLICATE_WINDOW_DAYS = 3

# Setup-Enable-Flags. MEAN_REVERSION disabled 2026-06-17:
# 30d-Window n=4 closed, WR 0% (4/4 loss), AvgLoss -2.70%.
# Score weakly ANTI-predictive in-sample, no live-validated edge. User skipt sie eh.
MEAN_REVERSION_ENABLED = False

# Quality filter for Telegram top-2 (setup-specific, data-driven)
TG_MIN_RR      = 1.5     # 2026-05-22: 2.0->1.5. Backtest: RR>=2.0 (WR 54.5%) gives
                         # NO edge over all (56.0%) but discards 67% of signals.
                         # 1.5 matches the strict-scan RR floor.
TG_MIN_UPSIDE  = 8.0
TG_MIN_SCORE   = {                       # Telegram top-2 quality filter per setup
    "BREAKOUT":      70,
    "VCP":           70,
    "SHORT_SQUEEZE": 65,
    "STAGE_2":       60,
    "MEAN_REVERSION": 70,   # Phase H — competes for top-2; wins mostly on no-breakout days
}
TG_MIN_SCORE_DEFAULT = 70

# Hard scan-level score gate per setup (drops candidates below threshold entirely)
SCAN_MIN_SCORE = {                       # Phase G: setup-specific quality gates
    "BREAKOUT":     70,                  # 63% WR / PF 2.09 (Phase A data)
    "VCP":          65,                  # Minervini quality, slightly looser gate
    "SHORT_SQUEEZE": 60,                 # momentum-driven, faster setups
    "STAGE_2":      55,                  # already passes strict structural filter
    "MEAN_REVERSION": 60,                # Phase H (MR early-returns before this gate; here for completeness)
}

# Ticker winrate file (generated by apex_backtest_v2.py)
TICKER_WINRATE_FILE = "ticker_winrate.json"

warnings.filterwarnings("ignore")

# =============================================================
# TELEGRAM CONFIG
# =============================================================
# Credentials ONLY from environment (GitHub Actions secrets). Never hardcoded
# to prevent token leaks via git history. Local dev: set env vars in shell.
TELEGRAM_TOKEN   = os.environ.get("TELEGRAM_TOKEN", "")
TELEGRAM_CHAT_ID = os.environ.get("TELEGRAM_CHAT_ID", "")
TELEGRAM_ENABLED = bool(TELEGRAM_TOKEN and TELEGRAM_CHAT_ID)


# =============================================================
# UTILS
# =============================================================
@contextlib.contextmanager
def suppress_output():
    old_out, old_err = sys.stdout, sys.stderr
    try:
        sys.stdout = io.StringIO()
        sys.stderr = io.StringIO()
        yield
    finally:
        sys.stdout = old_out
        sys.stderr = old_err


def normalize_ticker(ticker: str) -> str:
    return str(ticker).strip().upper().replace(".", "-")


def unique_keep_order(items):
    seen, out = set(), []
    for x in items:
        if x and x not in seen:
            seen.add(x)
            out.append(x)
    return out


def load_tickers(file_path):
    try:
        with open(file_path, "r", encoding="utf-8") as f:
            tickers = [normalize_ticker(line) for line in f if line.strip()]
        return unique_keep_order(tickers)
    except FileNotFoundError:
        return []


# Known dead tickers to skip (saves download time)
DEAD_TICKERS = {
    "TWTR", "FB", "SIVB", "FRC", "YHOO", "GGP", "CELG", "RTN", "STI",
    "VIAB", "APC", "RHT", "LLL", "AGN", "ETFC", "NBL", "ALXN", "BIIB",
    "ATVI", "XLNX", "DISH", "INFO", "DXC", "ABMD", "NKTR", "DWDP",
    "BHF", "DRE", "ARNC", "COTY", "FBHS", "WFM", "BBBY", "LEH",
    "FNM", "FRE", "CFC", "WB", "JDSU", "NOVL", "GENZ", "MFE", "EK",
    "SGP", "BCR", "SPLS", "RAI", "BHI", "SNI", "MON", "DPS", "TWX",
    "CA", "WYN", "XL", "ANDV", "SRCL", "AET", "COL", "SCG", "LLL",
    "PCLN", "ESRX", "NAVI", "GMCR", "ADS", "KORS", "TSS", "JEF",
}

# Tickers that consistently underperform in our backtest (2+ trades, WR ≤25%,
# negative cumulative PnL). Data-driven blacklist from apex_backtest_results.json
# (2024-01 to 2026-04 window). Revert by emptying this set.
BAD_PERFORMERS = {
    "VRSK", "ALGN", "DDOG", "OWL", "APTV", "FICO", "CMC", "KSS",
    "IFF", "GT", "FSLR", "MKTX", "AFG", "JKHY", "J", "KMI",
}


def clean_universe(tickers):
    cleaned = []
    for t in tickers:
        if not t or len(t) > 8:
            continue
        if "^" in t or "/" in t or "=" in t:
            continue
        if t in DEAD_TICKERS or t in BAD_PERFORMERS:
            continue
        cleaned.append(t)
    return unique_keep_order(cleaned)


def chunked(lst, size):
    for i in range(0, len(lst), size):
        yield lst[i:i + size]


def safe_float(x, default=0.0):
    try:
        return default if pd.isna(x) else float(x)
    except Exception:
        return default


def clean_nan_for_json(obj):
    """Recursively replace NaN/inf floats with None so JSON serialization is
    spec-compliant (json.dump's allow_nan default writes invalid 'NaN' tokens).
    Pandas DataFrame conversion in enrich_sector() turns Python None into NaN
    for numeric columns — this catches that and any other source."""
    if isinstance(obj, dict):
        return {k: clean_nan_for_json(v) for k, v in obj.items()}
    if isinstance(obj, list):
        return [clean_nan_for_json(x) for x in obj]
    if isinstance(obj, float):
        # Catches NaN (NaN != NaN) and +/- inf
        if obj != obj or obj == float("inf") or obj == float("-inf"):
            return None
    return obj


def percent_change(current, past):
    if pd.isna(current) or pd.isna(past) or past == 0:
        return None
    return ((float(current) / float(past)) - 1) * 100


# =============================================================
# LOCAL SIGNAL MEMORY (independent of git pull — fixes ENPH-duplicate bug)
# =============================================================
def load_signal_memory():
    """Returns {ticker: 'YYYY-MM-DD'} of signals from last 7 days."""
    from datetime import datetime, timedelta
    try:
        with open(SIGNAL_MEMORY, "r", encoding="utf-8") as f:
            data = json.load(f)
        # Prune entries older than 7 days
        cutoff = (datetime.now() - timedelta(days=7)).strftime("%Y-%m-%d")
        return {k: v for k, v in data.items() if v >= cutoff}
    except Exception:
        return {}


def save_signal_memory(mem):
    try:
        with open(SIGNAL_MEMORY, "w", encoding="utf-8") as f:
            json.dump(mem, f, indent=2, ensure_ascii=False)
    except Exception:
        pass


def update_signal_memory(tickers, today):
    """Add today's tickers to memory and persist."""
    mem = load_signal_memory()
    for t in tickers:
        mem[t] = today
    save_signal_memory(mem)


def signal_in_window(ticker, today, days=DUPLICATE_WINDOW_DAYS):
    """True if ticker was signaled within the last `days` days."""
    from datetime import datetime
    mem = load_signal_memory()
    if ticker not in mem:
        return False
    try:
        last = datetime.strptime(mem[ticker], "%Y-%m-%d")
        today_dt = datetime.strptime(today, "%Y-%m-%d")
        return abs((today_dt - last).days) <= days
    except Exception:
        return False


# =============================================================
# INDICATORS
# =============================================================
def rsi_wilder(series, period=14):
    """Wilder's smoothed RSI (more accurate than simple rolling mean)."""
    delta = series.diff()
    gain  = delta.clip(lower=0)
    loss  = -delta.clip(upper=0)
    # First value: simple mean
    avg_gain = gain.ewm(alpha=1/period, min_periods=period, adjust=False).mean()
    avg_loss = loss.ewm(alpha=1/period, min_periods=period, adjust=False).mean()
    rs = avg_gain / avg_loss.replace(0, float("nan"))
    return 100 - (100 / (1 + rs))


def macd(series, fast=12, slow=26, signal=9):
    ema_fast   = series.ewm(span=fast, adjust=False).mean()
    ema_slow   = series.ewm(span=slow, adjust=False).mean()
    macd_line  = ema_fast - ema_slow
    signal_line = macd_line.ewm(span=signal, adjust=False).mean()
    histogram  = macd_line - signal_line
    return macd_line, signal_line, histogram


def atr(df, period=14):
    hl  = df["High"] - df["Low"]
    hc  = (df["High"] - df["Close"].shift(1)).abs()
    lc  = (df["Low"]  - df["Close"].shift(1)).abs()
    tr  = pd.concat([hl, hc, lc], axis=1).max(axis=1)
    return tr.ewm(alpha=1/period, min_periods=period, adjust=False).mean()


# =============================================================
# NEW SETUP DETECTORS (Phase G: VCP, SHORT_SQUEEZE, STAGE_2_TRANSITION)
# =============================================================
def detect_vcp_setup(df, atr14_now, vol_ratio, ma50, ma150, close, high, atr_pct):
    """
    Minervini VCP (Volatility Contraction Pattern):
    Stock in Stage 2 + volatility shrinking 30%+ over 4-6 weeks + tight base + breakout.
    Returns dict with breakout_level/base_low/contraction% if detected, else None.
    """
    n = len(df)
    if n < 100: return None
    # 1. Stage 2 confirmation
    if not (close > ma150 > 0 and ma50 > ma150):
        return None
    # 2. ATR contraction 30%+ over 25 bars
    if "ATR14" not in df.columns: return None
    atr_old = df["ATR14"].iloc[-25]
    if pd.isna(atr_old) or atr_old <= 0: return None
    contraction = 1 - (atr14_now / atr_old)
    # 2026-05-28: loosened 0.30 -> 0.20. Backtest (2yr, VCP-isolated): 0.30 fired ~0 signals;
    # 0.20 gave n=9, WR 88.9%, PF 7.16. Still rare (~4-5/yr) but high quality. Other VCP
    # filters (20d-range <12%, vol>=1.2, atr_pct<=6%) keep it precise.
    if contraction < 0.20: return None
    # 3. Tight base: 20d range < 12%
    last20_high = df["High"].iloc[-21:-1].max()
    last20_low  = df["Low"].iloc[-21:-1].min()
    if last20_low <= 0: return None
    base_range_pct = (last20_high / last20_low - 1) * 100
    if base_range_pct > 12: return None
    # 4. Breakout: today's high touches above last 10d-high
    last10_high = df["High"].iloc[-11:-1].max()
    breakout_level = last10_high * 1.002
    if high < breakout_level * 0.998: return None
    # 5. Volume confirmation
    if vol_ratio < 1.2: return None
    # 6. Reasonable volatility (not extreme)
    if atr_pct > 6.0: return None
    return {
        "breakout_level":  breakout_level,
        "base_low":        last20_low,
        "contraction_pct": round(contraction * 100, 1),
        "base_range_pct":  round(base_range_pct, 1),
    }


def detect_short_squeeze_setup(df, short_pct, ma20, ma50, close, vol_ratio, rsi14):
    """
    Short Squeeze: high short interest + bullish technicals + accelerating move.
    Returns dict if detected, else None.
    """
    if short_pct is None or short_pct < 15.0: return None
    if not (close > ma20 and ma20 > ma50): return None  # uptrend
    n = len(df)
    if n < 6: return None
    closes = df["Close"].values
    perf_5d = (closes[-1] / closes[-6] - 1) * 100
    if perf_5d < 3.0: return None   # squeeze must be active
    if vol_ratio < 1.3: return None  # volume confirms
    if not (50 <= rsi14 <= 78): return None  # momentum but not extreme overbought
    return {
        "short_pct":       round(short_pct, 1),
        "perf_5d":         round(perf_5d, 1),
        "breakout_level":  df["High"].iloc[-11:-1].max() * 1.003,
    }


def detect_stage2_transition(df, ma150_series, close):
    """
    Weinstein Stage 2: long flat base (Stage 1) breaking into uptrend (Stage 2).
    Rare but powerful — flat MA150 turning up + breakout above base high.
    """
    n = len(df)
    if n < 252: return None   # need full year history
    # 1. Long flat base: 180d high/low ratio < 1.4 (lateral range)
    last180_close = df["Close"].iloc[-180:]
    base_high = float(last180_close.max())
    base_low  = float(last180_close.min())
    if base_low <= 0 or (base_high / base_low) > 1.4: return None
    # 2. MA150 was flat 5→1 months ago, now rising
    if ma150_series is None: return None
    try:
        ma150_now    = safe_float(ma150_series.iloc[-1])
        ma150_1m_ago = safe_float(ma150_series.iloc[-21])
        ma150_5m_ago = safe_float(ma150_series.iloc[-100])
    except Exception:
        return None
    if not (ma150_now and ma150_1m_ago and ma150_5m_ago): return None
    flat_change = abs(ma150_1m_ago / ma150_5m_ago - 1)
    if flat_change > 0.05: return None  # was flat (<5% change over 4 months)
    rise_change = ma150_now / ma150_1m_ago - 1
    if rise_change < 0.01: return None  # now rising
    # 3. Breakout above base high
    if close < base_high * 0.99: return None
    return {
        "base_high":       round(base_high, 2),
        "base_low":        round(base_low, 2),
        "ma150_rise_pct":  round(rise_change * 100, 2),
        "base_width_pct":  round((base_high / base_low - 1) * 100, 1),
    }


# =============================================================
# REVERSAL DETECTION (Phase F.1: 4 evidence-based factors → composite RSS)
# (Kept for compat — REVERSAL setup itself disabled in scan_ticker)
# =============================================================
def compute_reversal_indicators(df, rsi_series):
    """
    Returns dict of bullish-reversal signals:
      - bullish_divergence: price makes lower low, RSI makes higher low (Wilder)
      - hammer_candle: long lower shadow, body near top — selling rejected
      - bullish_engulfing: today's green body engulfs yesterday's red body
      - higher_low_structure: recent low > older low in last 30 days
      - obv_divergence: price lower low, OBV higher low (institutional accumulation)
      - selling_climax: recent big down-day with vol_ratio >= 2.5 (capitulation)
    """
    out = {
        "bullish_divergence":   False,
        "hammer_candle":        False,
        "bullish_engulfing":    False,
        "higher_low_structure": False,
        "obv_divergence":       False,
        "selling_climax":       False,
    }
    if df is None or len(df) < 30:
        return out

    closes = df["Close"].values
    highs  = df["High"].values
    lows   = df["Low"].values
    opens  = df["Open"].values
    vols   = df["Volume"].values
    n = len(closes)

    # --- 1. Bullish RSI-Divergence (Wilder classic) ---
    # Find lowest close in days [-30, -10] (old low) and [-10, -1] (new low)
    if rsi_series is not None and len(rsi_series) >= 30:
        rsi_vals = rsi_series.values
        old_win = closes[-30:-10]
        new_win = closes[-10:]
        old_low_idx = old_win.argmin() + (n - 30)
        new_low_idx = new_win.argmin() + (n - 10)
        if closes[new_low_idx] < closes[old_low_idx]:
            # Price made lower low → check if RSI made higher low
            if not pd.isna(rsi_vals[new_low_idx]) and not pd.isna(rsi_vals[old_low_idx]):
                if rsi_vals[new_low_idx] > rsi_vals[old_low_idx]:
                    out["bullish_divergence"] = True

    # --- 2. Hammer Candle ---
    # Body in upper 50%, lower shadow >= 2× body, decent range
    body = abs(closes[-1] - opens[-1])
    upper_shadow = highs[-1] - max(closes[-1], opens[-1])
    lower_shadow = min(closes[-1], opens[-1]) - lows[-1]
    total_range = highs[-1] - lows[-1]
    if total_range > 0 and body > 0:
        # Hammer needs significant lower shadow and small body up top
        if lower_shadow >= 2 * body and upper_shadow <= body * 0.5 and total_range / closes[-1] > 0.015:
            out["hammer_candle"] = True

    # --- 3. Bullish Engulfing ---
    # Yesterday red, today green AND today's body covers yesterday's body
    if n >= 2:
        prev_red   = closes[-2] < opens[-2]
        today_green = closes[-1] > opens[-1]
        if prev_red and today_green:
            if (closes[-1] >= opens[-2]) and (opens[-1] <= closes[-2]):
                out["bullish_engulfing"] = True

    # --- 4. Higher-Low Structure ---
    # Lowest low in [-30, -15] vs lowest low in [-15, -1]
    if n >= 30:
        old_segment = lows[-30:-15]
        new_segment = lows[-15:]
        if new_segment.min() > old_segment.min():
            # Plus: confirm we're not just sideways — old segment had a real low
            range_old = old_segment.max() - old_segment.min()
            avg_close = closes[-30:-15].mean()
            if range_old / avg_close > 0.03:  # at least 3% range
                out["higher_low_structure"] = True

    # --- 5. OBV-Divergence (On-Balance-Volume) ---
    # OBV cumulative: vol on up days adds, on down days subtracts
    if n >= 30:
        obv_changes = []
        for i in range(1, n):
            if closes[i] > closes[i-1]: obv_changes.append(vols[i])
            elif closes[i] < closes[i-1]: obv_changes.append(-vols[i])
            else: obv_changes.append(0)
        import numpy as np
        obv = np.cumsum([0] + obv_changes)
        # Check divergence on same lows as price
        old_close_low_idx = closes[-30:-10].argmin() + (n - 30)
        new_close_low_idx = closes[-10:].argmin() + (n - 10)
        if closes[new_close_low_idx] < closes[old_close_low_idx]:
            if obv[new_close_low_idx] > obv[old_close_low_idx]:
                out["obv_divergence"] = True

    # --- 6. Selling Climax: big down-day with extreme volume in last 5 days ---
    if n >= 21:
        vol20_avg = vols[-20:].mean()
        if vol20_avg > 0:
            for i in range(-5, 0):
                if closes[i] < closes[i-1]:  # down day
                    if vols[i] / vol20_avg >= 2.5:
                        out["selling_climax"] = True
                        break

    return out


def compute_reversal_strength_score(rev_signals):
    """Composite RSS — weights per indicator strength (higher = stronger evidence)."""
    rss = 0
    if rev_signals.get("bullish_divergence"):    rss += 25  # strongest
    if rev_signals.get("obv_divergence"):        rss += 20
    if rev_signals.get("higher_low_structure"):  rss += 15
    if rev_signals.get("bullish_engulfing"):     rss += 15
    if rev_signals.get("hammer_candle"):         rss += 12
    if rev_signals.get("selling_climax"):        rss += 13
    return rss


# =============================================================
# CATALYSTS (technical, computed from OHLCV — no API needed)
# =============================================================
def compute_technical_catalysts(df, atr14_now, vol_ratio):
    """
    Detects 4 evidence-based price-jump triggers from chart data:
      - Pocket Pivot (Morales/IBD): up-day where today's vol > max down-vol last 10d
      - Volume Climax: vol_ratio >= 3.0 today
      - Up-Gap: open today >2% above prev close
      - VCP (Minervini): ATR contracting >=30% over last 4 weeks
    Returns dict of signals + magnitudes.
    """
    out = {
        "pocket_pivot_recent": False,  # in last 5 trading days
        "volume_climax": False,
        "up_gap_pct": 0.0,
        "gap_signal": False,
        "vcp_strength": 0.0,    # 0..1
        "vcp_signal": False,
    }
    if df is None or len(df) < 21:
        return out

    closes = df["Close"].values
    vols   = df["Volume"].values
    opens  = df["Open"].values
    n = len(closes)

    # --- Pocket Pivot in last 5 days ---
    for i in range(1, 6):
        idx = n - i
        if idx < 11:
            break
        if closes[idx] <= closes[idx-1]:
            continue  # need up-day
        sub_close      = closes[idx-10:idx]
        sub_vol        = vols[idx-10:idx]
        sub_close_prev = closes[idx-11:idx-1]
        down_mask = sub_close < sub_close_prev
        if down_mask.any():
            max_down_vol = sub_vol[down_mask].max()
            if vols[idx] > max_down_vol:
                out["pocket_pivot_recent"] = True
                break

    # --- Volume Climax (today) ---
    out["volume_climax"] = vol_ratio >= 3.0

    # --- Up-Gap (today) ---
    if n >= 2 and closes[-2] > 0:
        out["up_gap_pct"] = (opens[-1] - closes[-2]) / closes[-2] * 100
        out["gap_signal"] = out["up_gap_pct"] > 2.0

    # --- VCP: ATR contraction over 4 weeks ---
    if "ATR14" in df.columns and n >= 21:
        atr_old = df["ATR14"].iloc[-21]
        if not pd.isna(atr_old) and atr_old > 0 and atr14_now > 0:
            contraction = 1 - (atr14_now / atr_old)
            out["vcp_strength"] = max(0.0, min(contraction, 1.0))
            out["vcp_signal"] = out["vcp_strength"] >= 0.30

    return out


# =============================================================
# DOWNLOAD
# =============================================================
def safe_download_single(ticker, period="1y"):
    try:
        with suppress_output():
            df = yf.download(ticker, period=period, auto_adjust=True,
                             progress=False, threads=False)
        return df.copy() if df is not None and not df.empty else None
    except Exception:
        return None


def extract_ticker_frame(raw_data, ticker):
    try:
        if raw_data is None or raw_data.empty:
            return None
        if isinstance(raw_data.columns, pd.MultiIndex):
            lvl0 = raw_data.columns.get_level_values(0).tolist()
            lvl1 = raw_data.columns.get_level_values(1).tolist()
            if ticker in lvl0:
                df = raw_data[ticker].copy()
            elif ticker in lvl1:
                df = raw_data.xs(ticker, axis=1, level=1).copy()
            else:
                return None
        else:
            df = raw_data.copy()

        required = ["Open", "High", "Low", "Close", "Volume"]
        if any(c not in df.columns for c in required):
            return None
        df = df[required].dropna().copy()
        return df if len(df) >= 30 else None
    except Exception:
        return None


# =============================================================
# MARKET REGIME
# =============================================================
def get_market_regime():
    # Download 2y to ensure enough data for MA200
    spy = safe_download_single("SPY", "2y")
    qqq = safe_download_single("QQQ", "2y")

    if spy is None or qqq is None:
        return {"risk_on": False, "mode": "UNKNOWN",
                "summary": "Market filter unavailable -> defaulting to RISK-OFF"}

    def regime(df):
        # Squeeze handles MultiIndex columns from yfinance
        c = df["Close"].squeeze() if hasattr(df["Close"], "squeeze") else df["Close"]
        if isinstance(c, pd.DataFrame):
            c = c.iloc[:, 0]
        c = c.dropna()
        if len(c) < 50:
            return "UNKNOWN"

        ma20  = c.rolling(20).mean()
        ma50  = c.rolling(50).mean()
        ma200 = c.rolling(200).mean() if len(c) >= 200 else None

        lc  = safe_float(c.iloc[-1])
        l20 = safe_float(ma20.iloc[-1])
        l50 = safe_float(ma50.iloc[-1])

        # Only use MA200 if we have enough data and it's not NaN
        if ma200 is not None:
            l200_val = ma200.iloc[-1]
            l200 = safe_float(l200_val) if not pd.isna(l200_val) else None
        else:
            l200 = None

        if l200 is not None:
            if lc > l20 > l50 > l200:   return "STRONG"
            if lc > l50 and l50 > l200: return "OK"
        else:
            # No MA200 — use MA50 only
            if lc > l20 > l50: return "STRONG"
            if lc > l50:       return "OK"
        return "WEAK"

    sr, qr = regime(spy), regime(qqq)
    risk_on = sr in {"STRONG", "OK"} and qr in {"STRONG", "OK"}

    if sr == "STRONG" and qr == "STRONG": mode = "BULLISH"
    elif risk_on:                          mode = "MIXED"
    else:                                  mode = "BEARISH"

    # SPY 20-day performance for relative strength calculation
    spy_close = spy["Close"].squeeze().dropna()
    spy_perf_20 = 0.0
    if len(spy_close) >= 21:
        spy_perf_20 = float((spy_close.iloc[-1] / spy_close.iloc[-21] - 1) * 100)

    # Sector ETF momentum (20d performance)
    sector_etfs = {
        "Energy":            "XLE",
        "Technology":        "XLK",
        "Healthcare":        "XLV",
        "Financials":        "XLF",
        "Industrials":       "XLI",
        "Consumer Defensive":"XLP",
        "Consumer Cyclical": "XLY",
        "Basic Materials":   "XLB",
        "Utilities":         "XLU",
        "Real Estate":       "XLRE",
        "Communication":     "XLC",
    }
    sector_momentum = {}
    try:
        etf_symbols = list(sector_etfs.values())
        etf_batch = yf.download(" ".join(etf_symbols), period="3mo",
                                group_by="ticker", auto_adjust=True,
                                progress=False, threads=True)
        for sector, etf in sector_etfs.items():
            try:
                if len(etf_symbols) == 1:
                    c = etf_batch["Close"].squeeze().dropna()
                else:
                    c = etf_batch[etf]["Close"].squeeze().dropna()
                if len(c) >= 21:
                    sector_momentum[sector] = round(float((c.iloc[-1] / c.iloc[-21] - 1) * 100), 2)
                else:
                    sector_momentum[sector] = 0.0
            except Exception:
                sector_momentum[sector] = 0.0
    except Exception:
        for sector in sector_etfs:
            sector_momentum[sector] = 0.0

    return {"risk_on": risk_on, "mode": mode,
            "summary": f"SPY={sr} | QQQ={qr} | Market={mode}",
            "spy_perf_20": spy_perf_20,
            "sector_momentum": sector_momentum}



def save_market_regime(market_regime):
    from datetime import datetime
    data = {
        "mode":    market_regime.get("mode", "UNKNOWN"),
        "risk_on": market_regime.get("risk_on", False),
        "summary": market_regime.get("summary", ""),
        "updated": datetime.now().strftime("%Y-%m-%d %H:%M")
    }
    with open("apex_market.json", "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2)


# =============================================================
# TARGET CALCULATION
# =============================================================
def find_target(df, buy_above, atr14, setup, risk_pct):
    """
    Finds a realistic price target using multiple methods:
    1. Previous swing highs (historical resistance)
    2. Fibonacci 1.272 / 1.618 extensions from last swing
    3. Round price levels (psychological resistance)
    4. ATH + buffer if near all-time high
    5. Fallback: RR-based with variable multiplier per setup

    Picks the nearest valid candidate above buy_above (min 4%, max 25% upside).
    """
    MIN_UPSIDE = 4.0    # minimum target distance %
    MAX_UPSIDE = 25.0   # maximum before considered unrealistic
    RR_FALLBACK = {"BREAKOUT": 2.0, "PRE-ROCKET": 2.5, "POSITION": 3.0}

    highs  = df["High"].values
    lows   = df["Low"].values
    n      = len(highs)

    candidates = []

    # --- Method 1: Swing highs (last 252 bars) ---
    SWING_W = 3
    lookback  = min(252, n - 1)
    start_idx = max(SWING_W, n - lookback)
    for i in range(start_idx, n - SWING_W):
        h = highs[i]
        if h <= buy_above:
            continue
        left  = highs[max(0, i - SWING_W) : i]
        right = highs[i + 1 : i + SWING_W + 1]
        if len(left) and len(right) and h > max(left) and h > max(right):
            candidates.append(round(h, 2))

    # --- Method 2: Fibonacci extensions ---
    # Find last significant swing low and swing high before buy_above
    recent = min(60, n - 1)
    swing_low  = float(min(lows[-recent:]))
    swing_high = float(max(highs[-recent:]))

    if swing_high > swing_low:
        move = swing_high - swing_low
        fib_1272 = round(swing_low + move * 1.272, 2)
        fib_1618 = round(swing_low + move * 1.618, 2)
        if fib_1272 > buy_above:
            candidates.append(fib_1272)
        if fib_1618 > buy_above:
            candidates.append(fib_1618)

    # --- Method 3: Round price levels ---
    # Find the next round numbers above buy_above
    def next_round_levels(price, above):
        levels = []
        # Determine magnitude of rounding
        if above > 500:   steps = [10, 25, 50, 100]
        elif above > 100: steps = [5, 10, 25, 50]
        elif above > 50:  steps = [2.5, 5, 10, 25]
        elif above > 10:  steps = [1, 2.5, 5, 10]
        else:             steps = [0.5, 1, 2.5, 5]
        for step in steps:
            rounded = math.ceil(above / step) * step
            # Add a few levels
            for i in range(5):
                lvl = round(rounded + i * step, 2)
                if lvl > above:
                    levels.append(lvl)
        return levels

    round_levels = next_round_levels(buy_above, buy_above)
    candidates.extend(round_levels)

    # --- Method 4: ATH + small buffer if near all-time high ---
    ath = float(df["High"].max())
    if ath > buy_above:
        candidates.append(round(ath, 2))
        candidates.append(round(ath * 1.05, 2))
        candidates.append(round(ath * 1.10, 2))

    # --- Step 5: Enforce minimum target = 2x ATR from entry ---
    # This ensures targets are not trivially close (avoids <5% upside)
    min_target_mult = {"BREAKOUT": 2.5, "PRE-ROCKET": 3.0, "POSITION": 4.0}
    atr_min_target  = buy_above + (atr14 * min_target_mult.get(setup, 2.5))
    atr_min_upside  = (atr_min_target / buy_above - 1) * 100

    # Use ATR minimum as floor for MIN_UPSIDE
    effective_min = max(MIN_UPSIDE, atr_min_upside)

    candidates = sorted(set(candidates))
    target = None
    for c in candidates:
        upside = (c / buy_above - 1) * 100
        if effective_min <= upside <= MAX_UPSIDE:
            target = c
            break

    # --- Fallback: ATR-based minimum target ---
    if target is None:
        rr_mult = RR_FALLBACK.get(setup, 2.0)
        rr_target = round(buy_above * (1 + (risk_pct * rr_mult) / 100), 2)
        # Take the larger of RR-based and ATR-based target
        target = max(rr_target, round(atr_min_target, 2))

    return target


# =============================================================
# TICKER WINRATE
# =============================================================
def load_ticker_winrate():
    try:
        with open(TICKER_WINRATE_FILE, "r", encoding="utf-8") as f:
            return json.load(f)
    except FileNotFoundError:
        return {}

TICKER_WINRATE = load_ticker_winrate()

# =============================================================
# CORE SCANNER
# =============================================================
def scan_ticker(ticker, data, market_regime, debug, sector_cache, relax=0):
    """
    relax=0  -> strict filters
    relax=1  -> slightly relaxed (fallback pass 1)
    relax=2  -> broad sweep (fallback pass 2, guarantees some output)
    """
    try:
        if data is None or data.empty:
            debug["empty_data"] += 1
            return None
        if len(data) < MIN_DATA_DAYS:
            debug["too_short"] += 1
            return None

        df = data.copy()
        df["MA20"]   = df["Close"].rolling(20).mean()
        df["MA50"]   = df["Close"].rolling(50).mean()
        df["MA150"]  = df["Close"].rolling(150).mean()
        df["VOL20"]  = df["Volume"].rolling(20).mean()
        df["RSI14"]  = rsi_wilder(df["Close"], 14)
        df["ATR14"]  = atr(df, 14)

        ml, sl, hist = macd(df["Close"])
        df["MACD"]      = ml
        df["MACD_SIG"]  = sl
        df["MACD_HIST"] = hist

        df = df.dropna(subset=["MA20","MA50","VOL20","RSI14","ATR14","MACD"]).copy()
        if len(df) < 30:
            debug["too_short_after_ind"] += 1
            return None

        l = df.iloc[-1]
        prev = df.iloc[-2]

        close   = safe_float(l["Close"])
        high    = safe_float(l["High"])
        vol     = safe_float(l["Volume"])
        vol20   = safe_float(l["VOL20"])
        ma20    = safe_float(l["MA20"])
        ma50    = safe_float(l["MA50"])
        ma150   = safe_float(l["MA150"])
        rsi14   = safe_float(l["RSI14"])
        atr14   = safe_float(l["ATR14"])
        macd_h  = safe_float(l["MACD_HIST"])
        macd_h_prev = safe_float(prev["MACD_HIST"])

        # ---- Basic filters ----
        if close < MIN_PRICE:
            debug["price_too_low"] += 1
            return None
        avg_dv = close * vol20
        if vol20 < MIN_AVG_VOLUME or avg_dv < MIN_DOLLAR_VOLUME:
            debug["volume_too_low"] += 1
            return None

        # ---- Lookback windows ----
        prev_20_high = safe_float(df["High"].iloc[-21:-1].max())
        prev_10_high = safe_float(df["High"].iloc[-11:-1].max())
        low_10       = safe_float(df["Low"].iloc[-10:].min())
        high_10      = safe_float(df["High"].iloc[-10:].max())
        high_52w     = safe_float(df["High"].iloc[-252:].max()) if len(df) >= 252 else safe_float(df["High"].max())
        pct_from_52w = ((close - high_52w) / high_52w * 100) if high_52w > 0 else 0

        perf_20  = percent_change(close, df["Close"].iloc[-21])
        perf_60  = percent_change(close, df["Close"].iloc[-61]) if len(df) >= 61 else None
        perf_120 = percent_change(close, df["Close"].iloc[-121]) if len(df) >= 121 else None

        if perf_20 is None:
            debug["perf_invalid"] += 1
            return None
        if perf_60  is None: perf_60  = perf_20
        if perf_120 is None: perf_120 = perf_60

        vol_ratio  = vol / vol20 if vol20 > 0 else 0
        base_range = percent_change(high_10, low_10)
        atr_pct    = (atr14 / close) * 100 if close > 0 else 0

        if base_range is None:
            debug["base_invalid"] += 1
            return None

        # ---- Technical catalysts (Phase A: pocket pivot, vol climax, gap, VCP) ----
        catalysts = compute_technical_catalysts(df, atr14, vol_ratio)

        # ---- Fundamental catalysts (Phase B: yfinance earnings/short/analyst) ----
        catalyst_signals = None
        if CATALYSTS_AVAILABLE:
            try:
                _raw = get_catalyst_data(ticker)
                catalyst_signals = derive_catalyst_signals(_raw)
            except Exception:
                catalyst_signals = None

        # ---- Indicator signals ----
        macd_bull  = macd_h > 0 and macd_h > macd_h_prev
        higher_tf  = ma150 > 0 and close >= ma150 * 0.95

        # ---- Per-setup RSI zones (tighter to reduce SL rate) ----
        # BREAKOUT: 45-68 (not overbought), PRE-ROCKET: 40-65, relax widens
        if relax == 0:
            rsi_breakout    = 45 <= rsi14 <= 68
            rsi_prerocket   = 40 <= rsi14 <= 65
            rsi_zone        = rsi_breakout  # default, overridden per setup below
        else:
            rsi_breakout    = 40 <= rsi14 <= 72
            rsi_prerocket   = 38 <= rsi14 <= 72
            rsi_zone        = 38 <= rsi14 <= 75

        # ---- Trend filters (loosen with relax) ----
        if relax == 0:
            trend_ok   = close > ma20 and ma20 > ma50 * 0.99
            near_high  = close >= prev_20_high * 0.93
            base_ok    = base_range <= 8     # tighter: was 22
        elif relax == 1:
            trend_ok   = close > ma50
            near_high  = close >= prev_20_high * 0.88
            base_ok    = base_range <= 15
        else:
            trend_ok   = close > ma150 * 0.90 if ma150 > 0 else close > ma50
            near_high  = close >= prev_20_high * 0.80
            base_ok    = base_range <= 25

        short_near_high = close >= prev_10_high * 0.95
        breakout_touch  = high >= prev_20_high * 0.995
        vol_ok          = vol_ratio >= (0.7 if relax >= 1 else 1.0)
        expansion_vol   = vol_ratio >= 1.1
        momentum_ok     = perf_20 > 0 and perf_60 > 0

        # ---- REVERSAL DISABLED (Phase G: replaced by VCP/SQUEEZE/STAGE_2) ----
        reversal_setup = False
        rss = 0
        rev_indicators = {}

        # ---- MEAN_REVERSION setup (Phase H, 2026-05-22) — own gates, BEFORE breakout hard-exits ----
        # Uptrend pullback, oversold, turning up. Postmortem-informed to avoid REVERSAL's
        # falling-knife failures. Backtest (810 tickers, ~16mo): WR 48.9% / PF 1.84, n=47,
        # beats disabled REVERSAL (30%) by +19pp; profitable in 2/3 sub-periods.
        # NOTE: emits ALL structurally-valid MR (no scan score-gate) to match the validated
        # baseline. MR score is weakly ANTI-predictive in-sample (higher score != higher WR) —
        # revisit the score formula once live out-of-sample data accumulates.
        ma150_prev = safe_float(df["MA150"].iloc[-11]) if len(df) >= 11 else 0.0
        prev_close = safe_float(prev["Close"])
        _mr_en = (catalyst_signals or {}).get("earnings_next_days")
        mr_fire = (
            MEAN_REVERSION_ENABLED
            and ma150 > 0 and ma150_prev > 0 and ma150 > ma150_prev and close > ma150  # uptrend
            and close < ma20                                                       # pulled back
            and rsi14 < 38                                                         # oversold
            and close > prev_close                                                 # turning up
            and base_range < 15                                                    # no wide knife
            and perf_120 < 80                                                      # not extended
            and ((_mr_en is None) or (_mr_en >= 7))                                # earnings blackout
        )
        if mr_fire:
            mr_buy   = round(close * 1.002, 2)
            mr_stop  = round(low_10 * 0.985, 2)
            mr_riskp = (mr_buy - mr_stop) / mr_buy * 100 if mr_buy > 0 else 99
            mr_tgt   = round(max(ma20, high_10), 2)
            mr_rr    = (mr_tgt - mr_buy) / (mr_buy - mr_stop) if mr_buy > mr_stop else 0
            mr_up    = ((mr_tgt / mr_buy) - 1) * 100 if mr_buy > 0 else 0
            if 2.0 <= mr_riskp <= 10.0 and mr_rr >= 1.5:
                mr_score  = 50.0
                mr_score += max(0.0, 40 - rsi14) * 1.5            # oversold depth (fixed anchor)
                mr_score += min(mr_rr, 4.0) * 6                    # RR
                if close > ma50: mr_score += 8                     # shallow pullback = healthier
                if macd_h > macd_h_prev: mr_score += 6             # MACD hist turning up
                if catalysts.get("pocket_pivot_recent"): mr_score += 8
                mr_score += min(max(perf_120, 0.0), 40.0) * 0.2    # uptrend strength
                _mr_dr = high - safe_float(l["Low"])
                _mr_cs = (close - safe_float(l["Low"])) / _mr_dr if _mr_dr > 0 else 0.5
                _mr_id = (high <= safe_float(prev["High"])) and (safe_float(l["Low"]) >= safe_float(prev["Low"]))
                debug["passed"] += 1
                return {
                    "ticker": ticker, "setup": "MEAN_REVERSION",
                    "action": f"BUY above {mr_buy:.2f} (mean-reversion bounce)",
                    "price": round(close, 2), "buy_above": mr_buy, "stop": mr_stop,
                    "target": mr_tgt, "upside_pct": round(mr_up, 1),
                    "risk_pct": round(mr_riskp, 1), "rr": round(mr_rr, 2),
                    "horizon": "2-4 weeks", "rsi": round(rsi14, 1),
                    "macd_bull": "YES" if macd_bull else "NO",
                    "vol_ratio": round(vol_ratio, 2), "avg_dv_m": round(avg_dv / 1_000_000, 2),
                    "perf_20d": round(perf_20, 1), "perf_60d": round(perf_60, 1),
                    "perf_120d": round(perf_120, 1), "base_range": round(base_range, 1),
                    "relax_level": relax, "score": round(mr_score, 1),
                    "cat_pocket_pivot": catalysts["pocket_pivot_recent"],
                    "cat_vol_climax": catalysts["volume_climax"],
                    "cat_gap_pct": round(catalysts["up_gap_pct"], 2),
                    "cat_vcp_strength": round(catalysts["vcp_strength"], 2),
                    "cat_earnings_blackout": (catalyst_signals or {}).get("earnings_in_blackout", False),
                    "cat_earnings_beat": (catalyst_signals or {}).get("earnings_beat_recent", False),
                    "cat_earnings_next_days": (catalyst_signals or {}).get("earnings_next_days"),
                    "cat_short_pct": (catalyst_signals or {}).get("short_pct_float"),
                    "cat_analyst_upside": (catalyst_signals or {}).get("analyst_target_upside"),
                    "movement_class": "MEAN_REVERSION", "movement_bonus": 0,
                    "closing_strength": round(_mr_cs, 2), "inside_day": _mr_id,
                    "vcp_contraction": None, "vcp_base_range": None,
                    "squeeze_short_pct": None, "squeeze_perf_5d": None,
                    "stage2_ma150_rise": None, "stage2_base_width": None,
                }

        # ---- BREAKOUT eligibility (computed early so the base-gate can be setup-specific) ----
        buy_above_preview = prev_20_high * 1.002
        breakout_close    = close >= buy_above_preview * 0.99
        breakout_setup    = breakout_touch and higher_tf and rsi_breakout and breakout_close

        # ---- Hard exits ----
        if not trend_ok:   debug["fail_trend"]   += 1; return None
        if not vol_ok:     debug["fail_volume"]   += 1; return None
        if not rsi_zone:   debug["fail_rsi"]      += 1; return None
        if relax == 0 and not momentum_ok: debug["fail_momentum"] += 1; return None
        # Base-gate is SETUP-SPECIFIC (2026-05-22): BREAKOUT uses <=22, others keep strict <=8.
        # Backtest (2yr, BREAKOUT-isolated): base<=22 vs <=8 -> n 64->163, WR 48.4->52.1%,
        # PF 1.17->1.68. The 19.4 tightening to <=8 choked BREAKOUT without improving WR.
        if relax == 0:
            base_cap = 22 if breakout_setup else 8
            if base_range > base_cap: debug["fail_base"] += 1; return None
        if atr_pct > 15:   debug["atr_too_high"]  += 1; return None

        # ---- Setup detection (Phase G: 4 setups with priority order) ----
        # BREAKOUT detected above (buy_above_preview / breakout_close / breakout_setup)

        # Short interest from Phase B catalyst data (may be None)
        short_pct_val = (catalyst_signals or {}).get("short_pct_float")

        # Detect all 3 new setups
        vcp_data     = detect_vcp_setup(df, atr14, vol_ratio, ma50, ma150, close, high, atr_pct)
        squeeze_data = detect_short_squeeze_setup(df, short_pct_val, ma20, ma50, close, vol_ratio, rsi14)
        stage2_data  = detect_stage2_transition(df, df.get("MA150"), close)

        # PRE-ROCKET + POSITION still disabled
        pre_rocket_setup = False
        position_setup   = False

        # Priority: STAGE_2 > VCP > SQUEEZE > BREAKOUT (rare = high conviction)
        if stage2_data:
            chosen_setup = "STAGE_2"
        elif vcp_data:
            chosen_setup = "VCP"
        elif squeeze_data:
            chosen_setup = "SHORT_SQUEEZE"
        elif breakout_setup:
            chosen_setup = "BREAKOUT"
        else:
            debug["fail_setup"] += 1
            return None

        # Market filter: RISK-OFF → only BREAKOUT-style allowed (STAGE_2/VCP need trend)
        if not market_regime["risk_on"] and relax == 0:
            # All Phase G setups need trend — RISK-OFF would block all anyway via trend_ok
            pass

        # ---- Entry / Stop / Target (Phase G: 4 setups) ----

        if chosen_setup == "STAGE_2":
            # Weinstein Stage 2: long-base breakout, wider stop & target
            setup     = "STAGE_2"
            horizon   = "8-16 weeks"
            buy_above = round(stage2_data["base_high"] * 1.005, 2)
            action    = f"BUY above {buy_above:.2f} (Stage 2 base breakout)"
            stop      = round(max(ma150, stage2_data["base_low"]) * 0.97, 2)
            risk_pct  = (buy_above - stop) / buy_above * 100 if buy_above > 0 else 99
            if risk_pct < 3.0:
                stop = buy_above * 0.92; risk_pct = 8.0  # wider stop OK for Stage 2
            elif risk_pct > 15.0:
                debug["risk_too_high"] += 1; return None
            # Target: measured move (base_high + base_width)
            base_width = stage2_data["base_high"] - stage2_data["base_low"]
            target = round(stage2_data["base_high"] + base_width * 1.5, 2)
            target = min(target, buy_above * 1.40)  # cap at +40%

        elif chosen_setup == "VCP":
            # Minervini VCP: tight base breakout, tight stop, aggressive target
            setup     = "VCP"
            horizon   = "4-8 weeks"
            buy_above = round(vcp_data["breakout_level"], 2)
            action    = f"BUY above {buy_above:.2f} (VCP)"
            stop      = round(vcp_data["base_low"] * 0.99, 2)
            risk_pct  = (buy_above - stop) / buy_above * 100 if buy_above > 0 else 99
            if risk_pct < 3.0:
                stop = buy_above * 0.95; risk_pct = 5.0
            elif risk_pct > 8.0:
                debug["risk_too_high"] += 1; return None
            # Target: 3-5x ATR or +15-20%
            atr_target = buy_above + (atr14 * 4.0)
            pct_target = buy_above * 1.18
            target = round(max(atr_target, pct_target), 2)

        elif chosen_setup == "SHORT_SQUEEZE":
            # Short Squeeze: above MA20, momentum, tight risk
            setup     = "SHORT_SQUEEZE"
            horizon   = "2-4 weeks"
            buy_above = round(squeeze_data["breakout_level"], 2)
            action    = f"BUY above {buy_above:.2f} (squeeze, {squeeze_data['short_pct']:.0f}% short)"
            stop      = round(ma20 * 0.98, 2)
            risk_pct  = (buy_above - stop) / buy_above * 100 if buy_above > 0 else 99
            if risk_pct < 3.0:
                stop = buy_above * 0.96; risk_pct = 4.0
            elif risk_pct > 8.0:
                debug["risk_too_high"] += 1; return None
            # Target: extension toward 52w high or +15%
            tgt_52w = high_52w * 0.95
            target = round(min(tgt_52w, buy_above * 1.20), 2) if tgt_52w > buy_above else round(buy_above * 1.15, 2)

        else:  # BREAKOUT (existing logic)
            setup     = "BREAKOUT"
            horizon   = "1-3 weeks"
            buy_above = prev_20_high * 1.002

            stop_candidate = low_10 * 0.995
            atr_pct_val    = (atr14 / buy_above) * 100 if buy_above > 0 else 5.0
            min_dist_pct   = max(3.0, atr_pct_val * 1.5)
            multiplier     = 1.5
            candidate_dist = ((buy_above - stop_candidate) / buy_above * 100
                              if buy_above > 0 else 99)

            if candidate_dist < min_dist_pct:
                stop = buy_above * (1 - min_dist_pct / 100)
            elif candidate_dist > 6:
                stop = buy_above - (atr14 * multiplier)
            else:
                stop = stop_candidate

            risk_pct = (buy_above - stop) / buy_above * 100 if buy_above > 0 else 99
            if risk_pct < 3.0:
                stop = buy_above * 0.97; risk_pct = 3.0
            elif risk_pct > 10.0:
                debug["risk_too_high"] += 1; return None

            action  = f"BUY above {buy_above:.2f}"
            target  = find_target(df, buy_above, atr14, setup, risk_pct)

        upside_pct = ((target / buy_above) - 1) * 100
        rr = upside_pct / risk_pct if risk_pct > 0 else 0

        min_rr = 1.5 if relax == 0 else 1.2
        if rr < min_rr:
            debug["rr_too_low"] += 1
            return None

        # Minimum upside filter per setup
        min_upside = 12.0 if setup == "STAGE_2" else 8.0
        if upside_pct < min_upside:
            debug["upside_too_low"] = debug.get("upside_too_low", 0) + 1
            return None

        # ---- Movement Classification (Phase E + G) ----
        # Sub-classify each setup for additional discrimination
        movement_class = "STANDARD"
        movement_bonus = 0
        if setup == "BREAKOUT":
            # SCORE_REALIGN live 2026-06-14 (Backtest 2 Jahre validiert:
            # WR 51.9%->53.8%, PF 1.66->1.78, n -6% mit 77 % Loser-Anteil der weggefallenen).
            # Bucketed nach gemessenen Live-WR-Kohorten:
            if perf_120 < 0:
                movement_class = "WEAK_BREAKOUT"; movement_bonus = -15  # n=7 zu klein, lassen
            elif perf_120 <= 25:
                movement_class = "DEADZONE_BREAKOUT"; movement_bonus = -3   # 44 % WR n=27 (war +5)
            elif perf_120 <= 50:
                movement_class = "SWEET_BREAKOUT"; movement_bonus = 15  # 71 % WR n=24
            else:  # >50 extended
                movement_class = ("POWER_BREAKOUT" if pct_from_52w > -2 else "EMERGING_BREAKOUT")
                movement_bonus = 8
        elif setup == "VCP":
            # VCP needs strong long-term trend (Stage 2 already verified)
            movement_class = "VCP_TIGHT" if vcp_data["base_range_pct"] <= 8 else "VCP_WIDE"
            movement_bonus = 10 if movement_class == "VCP_TIGHT" else 5
        elif setup == "SHORT_SQUEEZE":
            movement_class = "SQUEEZE_HIGH" if short_pct_val and short_pct_val >= 20 else "SQUEEZE_MED"
            movement_bonus = 12 if movement_class == "SQUEEZE_HIGH" else 6
        elif setup == "STAGE_2":
            movement_class = "STAGE_2_BREAKOUT"
            movement_bonus = 15  # always quality (passed strict gate)

        # ---- Closing-Strength: where did today close in day-range? ----
        # >0.75 = strong close near high (real breakout)
        # <0.5 = weak close near low (spike-reversal-trap, common in quick-stops)
        day_range = high - safe_float(l["Low"])
        if day_range > 0:
            closing_strength = (close - safe_float(l["Low"])) / day_range
        else:
            closing_strength = 0.5
        closing_bonus = 0
        if closing_strength > 0.75:
            closing_bonus = 5
        elif closing_strength < 0.5:
            closing_bonus = -10  # spike-trap penalty

        # ---- Inside-Day-Detection: today's range fully inside yesterday's ----
        # Means consolidation, not a true breakout — common false-breakout trigger
        prev_high = safe_float(prev["High"])
        prev_low  = safe_float(prev["Low"])
        today_low = safe_float(l["Low"])
        inside_day = (high <= prev_high) and (today_low >= prev_low)
        inside_day_penalty = -8 if (inside_day and setup == "BREAKOUT") else 0

        # ---- Score: setup-specific calculation (Phase G: 4 setups) ----
        if setup == "STAGE_2":
            # Weinstein Stage 2 — rare, high-conviction
            score = 30.0  # base (highest, only fires under strict conditions)
            score += min(stage2_data["ma150_rise_pct"], 5) * 3  # MA150 rise momentum
            score += 10 if stage2_data["base_width_pct"] < 25 else 5  # tight base bonus
            score += 8 if higher_tf else 0
            score += 8 if macd_bull else 0
            score += 6 if 48 <= rsi14 <= 68 else (3 if rsi_zone else 0)
            score += 5 if market_regime["risk_on"] else 0
            score += min(max(perf_20, 0), 20) * 0.5
            score += min(vol_ratio, 3.0) * 4
            score += min(rr, 5.0) * 4
            # Phase A catalysts apply
            if catalysts["pocket_pivot_recent"]: score += 10
            if catalysts["volume_climax"]:       score += 5
            if catalysts["gap_signal"]:          score += 8

        elif setup == "VCP":
            # Minervini VCP — quality contraction breakout
            score = 25.0  # base
            score += vcp_data["contraction_pct"] * 0.2  # contraction strength (max ~20)
            score += 10 if vcp_data["base_range_pct"] <= 8 else 5  # tight base bonus
            score += 8 if higher_tf else 0
            score += 8 if macd_bull else 0
            score += 6 if 48 <= rsi14 <= 68 else (3 if rsi_zone else 0)
            score += 5 if market_regime["risk_on"] else 0
            score += min(max(perf_60, 0), 35) * 0.4
            score += min(max(perf_120, 0), 50) * 0.2
            score += min(vol_ratio, 3.0) * 4
            score += min(rr, 5.0) * 4
            # Phase A catalysts apply (VCP is the perfect Pocket-Pivot setup)
            if catalysts["pocket_pivot_recent"]: score += 12  # PP in VCP is very bullish
            if catalysts["volume_climax"]:       score += 5
            if catalysts["gap_signal"]:          score += 8

        elif setup == "SHORT_SQUEEZE":
            # Short Squeeze — momentum + forced covering
            score = 20.0  # base
            score += min(squeeze_data["short_pct"] - 15, 20) * 0.5  # short% above 15
            score += min(squeeze_data["perf_5d"], 15) * 0.6        # recent momentum
            score += 8 if higher_tf else 0
            score += 8 if macd_bull else 0
            score += 8 if expansion_vol else (4 if vol_ratio >= 1.0 else 0)
            score += 6 if 50 <= rsi14 <= 70 else (3 if 45 <= rsi14 <= 78 else 0)
            score += 5 if market_regime["risk_on"] else 0
            score += min(vol_ratio, 3.0) * 4
            score += min(rr, 5.0) * 4
            # Phase A catalysts apply
            if catalysts["pocket_pivot_recent"]: score += 10
            if catalysts["volume_climax"]:       score += 8  # extreme vol = squeeze in progress
            if catalysts["gap_signal"]:          score += 8

        else:  # BREAKOUT (SCORE_REALIGN live 2026-06-14)
            score = 0.0
            score += 20
            score += 8  if higher_tf else 0
            score += 8  if expansion_vol else (4 if vol_ratio >= 1.0 else 0)
            score += 8  if macd_bull else 0
            # Realign: RSI 48-72 (war 48-68). RSI>=70 zeigt 75 % WR n=12 in Live-Daten.
            score += 6  if 48 <= rsi14 <= 72 else (3 if rsi_zone else 0)
            score += 5  if market_regime["risk_on"] else 0
            score += min(max(perf_20, 0), 20)  * 0.8
            score += min(max(perf_60, 0), 35)  * 0.5
            score += min(max(perf_120, 0), 50) * 0.2
            score += min(vol_ratio, 3.0) * 4
            score += min(rr, 5.0) * 4
            score += 3 if short_near_high else 0
            if catalysts["pocket_pivot_recent"]: score += 10
            if catalysts["volume_climax"]:       score += 5
            if catalysts["gap_signal"]:          score += 8
            if catalysts["vcp_signal"]:          score += 5

        # Historical winrate bonus (both setups)
        wr_data = TICKER_WINRATE.get(ticker)
        if wr_data and wr_data.get("total", 0) >= 2:
            wr = wr_data["winrate"]
            score += (wr - 50) * 0.2  # +10 for 100% WR, -10 for 0% WR

        # RS and Sector bonuses ONLY for BREAKOUT (mean-reversion REVERSAL bets
        # AGAINST momentum — high RS/Sector mom would penalize valid REVERSAL setups)
        if setup == "BREAKOUT":
            # 1. Relative Strength vs SPY
            spy_perf = market_regime.get("spy_perf_20", 0)
            rs = perf_20 - spy_perf  # positive = outperforming market
            if rs >= 5:    score += 8   # strong outperformer
            elif rs >= 2:  score += 5
            elif rs >= 0:  score += 2
            elif rs < -5:  score -= 5   # significant underperformer
            elif rs < -2:  score -= 2

            # 4. Sector Momentum — sector looked up from cache
            sector_mom = market_regime.get("sector_momentum", {})
            ticker_sector = sector_cache.get(ticker, "Unknown")
            sector_map = {
                "Energy": "Energy", "Technology": "Technology",
                "Healthcare": "Healthcare", "Financial Services": "Financials",
                "Industrials": "Industrials", "Consumer Defensive": "Consumer Defensive",
                "Consumer Cyclical": "Consumer Cyclical", "Basic Materials": "Basic Materials",
                "Utilities": "Utilities", "Real Estate": "Real Estate",
                "Communication Services": "Communication",
            }
            mapped = sector_map.get(ticker_sector, ticker_sector)
            sec_perf = sector_mom.get(mapped, 0)
            if sec_perf >= 5:    score += 6
            elif sec_perf >= 2:  score += 3
            elif sec_perf < -5:  score -= 5
            elif sec_perf < -2:  score -= 2

        # ---- Phase B fundamental catalysts (earnings, short, analyst) ----
        if catalyst_signals is not None:
            score += score_delta_for_catalyst_signals(catalyst_signals, setup)

        # ---- Phase E quality adjustments ----
        score += movement_bonus      # POWER/EMERGING/WEAK/BOUNCE/DEAD_CAT
        score += closing_bonus       # close-near-high reward / close-near-low penalty
        score += inside_day_penalty  # consolidation inside prev day -> false breakout risk

        # ---- SCORE_REBUILD live (2026-06-20, Backtest-validiert) ----
        # Catalyst-gated Extension-Penalty: ueberdehnte BREAKOUTs (perf_120>50) OHNE starken
        # Catalyst sind Late-Entries (Backtest 100-110-Trough: Loser perf_120 +61% vs Winner +33%).
        # -12 -> Plateau WR(100+) 47%->54%, Monotonie -15pp->-0pp, alle Signale erhalten (Sweep-Optimum).
        # Carve-Out schuetzt Semi/AI-Capex-Winner (what_to_replicate). Live HAT zusaetzlich
        # analyst_upside>15 (Backtest skippt analyst) -> Carve-Out live robuster.
        if setup == "BREAKOUT" and perf_120 > 50:
            _gap_rb     = catalysts.get("up_gap_pct", 0) or 0
            _analyst_rb = (catalyst_signals or {}).get("analyst_target_upside") or 0
            strong_catalyst = (
                (catalyst_signals or {}).get("earnings_beat_recent") or
                _analyst_rb > 15 or
                (catalysts.get("pocket_pivot_recent") and catalysts.get("volume_climax")) or
                _gap_rb >= 5.0
            )
            if not strong_catalyst:
                score -= 12.0

        # (RSS removed — REVERSAL setup disabled in Phase G)

        # ---- Hard score gate (per setup) ----
        min_score = SCAN_MIN_SCORE.get(setup, 0)
        if score < min_score:
            debug["score_below_gate"] = debug.get("score_below_gate", 0) + 1
            return None

        debug["passed"] += 1

        return {
            "ticker":           ticker,
            "setup":            setup,
            "action":           action,
            "price":            round(close, 2),
            "buy_above":        round(buy_above, 2),
            "stop":             round(stop, 2),
            "target":           round(target, 2),
            "upside_pct":       round(upside_pct, 1),
            "risk_pct":         round(risk_pct, 1),
            "rr":               round(rr, 2),
            "horizon":          horizon,
            "rsi":              round(rsi14, 1),
            "macd_bull":        "YES" if macd_bull else "NO",
            "vol_ratio":        round(vol_ratio, 2),
            "avg_dv_m":         round(avg_dv / 1_000_000, 2),
            "perf_20d":         round(perf_20, 1),
            "perf_60d":         round(perf_60, 1),
            "perf_120d":        round(perf_120, 1),
            "base_range":       round(base_range, 1),
            "relax_level":      relax,
            "score":            round(score, 1),
            # Catalyst signals for visibility/Telegram
            "cat_pocket_pivot": catalysts["pocket_pivot_recent"],
            "cat_vol_climax":   catalysts["volume_climax"],
            "cat_gap_pct":      round(catalysts["up_gap_pct"], 2),
            "cat_vcp_strength": round(catalysts["vcp_strength"], 2),
            "cat_earnings_blackout": (catalyst_signals or {}).get("earnings_in_blackout", False),
            "cat_earnings_beat": (catalyst_signals or {}).get("earnings_beat_recent", False),
            "cat_earnings_next_days": (catalyst_signals or {}).get("earnings_next_days"),
            "cat_short_pct":    (catalyst_signals or {}).get("short_pct_float"),
            "cat_analyst_upside": (catalyst_signals or {}).get("analyst_target_upside"),
            # Phase E quality classification
            "movement_class":   movement_class,
            "movement_bonus":   movement_bonus,
            "closing_strength": round(closing_strength, 2),
            "inside_day":       inside_day,
            # Phase G: setup-specific metadata
            "vcp_contraction":  vcp_data["contraction_pct"] if chosen_setup == "VCP" else None,
            "vcp_base_range":   vcp_data["base_range_pct"] if chosen_setup == "VCP" else None,
            "squeeze_short_pct": squeeze_data["short_pct"] if chosen_setup == "SHORT_SQUEEZE" else None,
            "squeeze_perf_5d":  squeeze_data["perf_5d"] if chosen_setup == "SHORT_SQUEEZE" else None,
            "stage2_ma150_rise": stage2_data["ma150_rise_pct"] if chosen_setup == "STAGE_2" else None,
            "stage2_base_width": stage2_data["base_width_pct"] if chosen_setup == "STAGE_2" else None,
        }

    except Exception as e:
        debug["processing_error"] += 1
        return None


# =============================================================
# SECTOR
# =============================================================
def load_sector_cache():
    try:
        with open(SECTOR_CACHE, "r", encoding="utf-8") as f:
            d = json.load(f)
            return d if isinstance(d, dict) else {}
    except Exception:
        return {}


def save_sector_cache(cache):
    try:
        with open(SECTOR_CACHE, "w", encoding="utf-8") as f:
            json.dump(cache, f, ensure_ascii=False, indent=2)
    except Exception:
        pass


def enrich_sector(candidates):
    if not candidates:
        return candidates
    cache = load_sector_cache()
    for row in candidates:
        t = row["ticker"]
        # 2026-06-01 fix: retry "Unknown" entries (yfinance temp-fails got cached permanently).
        # Don't cache failures — let next scan re-try. Only cache successful lookups.
        if t not in cache or cache.get(t) == "Unknown":
            try:
                with suppress_output():
                    info = yf.Ticker(t).info
                if isinstance(info, dict) and info.get("sector"):
                    cache[t] = info["sector"]
            except Exception:
                pass
        row["sector"] = cache.get(t, "Unknown")
    save_sector_cache(cache)
    df = pd.DataFrame(candidates).sort_values(
        ["score", "rr", "vol_ratio"], ascending=False
    ).reset_index(drop=True)
    # DataFrame coerces None → NaN in numeric columns; clean back for JSON safety
    return clean_nan_for_json(df.to_dict("records"))


# =============================================================
# SCAN PIPELINE WITH ADAPTIVE FALLBACK
# =============================================================
def run_scan(tickers, market_regime):
    """
    Three-pass adaptive scan:
      Pass 0 – strict filters
      Pass 1 – relaxed filters   (if pass 0 < MIN_SIGNALS)
      Pass 2 – broad sweep       (if pass 1 < MIN_SIGNALS)
    Returns list of candidates (best pass used).
    """
    all_frames = {}
    debug = Counter()

    batches = list(chunked(tickers, BATCH_SIZE))
    for batch in tqdm(batches, desc="Downloading"):
        raw = None
        try:
            with suppress_output():
                raw = yf.download(
                    tickers=" ".join(batch),
                    period=HISTORY_PERIOD,
                    auto_adjust=True,
                    progress=False,
                    threads=True,
                    group_by="ticker",
                )
        except Exception:
            pass

        for ticker in batch:
            frame = extract_ticker_frame(raw, ticker)
            if frame is not None:
                all_frames[ticker] = frame

    print(f"  Usable frames: {len(all_frames)} / {len(tickers)}")

    sector_cache = load_sector_cache()

    for relax in range(3):
        candidates = []
        pass_debug = Counter()
        for ticker, frame in all_frames.items():
            result = scan_ticker(ticker, frame, market_regime, pass_debug, sector_cache, relax=relax)
            if result is not None:
                candidates.append(result)

        debug += pass_debug

        if len(candidates) >= MIN_SIGNALS:
            if relax > 0:
                print(f"  Note: filters relaxed to level {relax} to find signals.")
            break
        else:
            print(f"  Pass {relax}: {len(candidates)} signals – relaxing filters...")

    # Deduplicate tickers
    seen, unique = set(), []
    for c in sorted(candidates, key=lambda x: x["score"], reverse=True):
        if c["ticker"] not in seen:
            seen.add(c["ticker"])
            unique.append(c)

    return unique[:MAX_SIGNALS], debug


def apply_sector_cap(candidates):
    """Sector diversification applied after enrich_sector() has set real sector values."""
    sector_count = {}
    diversified  = []
    for c in candidates:
        sector = c.get("sector", "Unknown")
        setup  = c.get("setup", "")
        limit  = 2  # All Phase G setups (BREAKOUT/VCP/SQUEEZE/STAGE_2): max 2 per sector
        if sector_count.get(sector, 0) < limit:
            sector_count[sector] = sector_count.get(sector, 0) + 1
            diversified.append(c)
    return diversified


# =============================================================
# DISPLAY
# =============================================================
def print_signals(candidates):
    if not candidates:
        print("\nNo trade setups found today.")
        return

    print(f"\n{'='*72}")
    print(f"  TOP TRADE SIGNALS  ({len(candidates)} found)")
    print(f"{'='*72}")

    for i, row in enumerate(candidates[:TOP_RESULTS], 1):
        rl = row.get("relax_level", 0)
        rl_str = "" if rl == 0 else f"  [filter-relax={rl}]"
        print(f"\n{i}. {row['ticker']}  |  {row['setup']}  |  {row.get('sector','?')}  |  Score: {row['score']}{rl_str}")
        print(f"   Action     : {row['action']}")
        print(f"   Price now  : {row['price']}   Buy above: {row['buy_above']}   Stop: {row['stop']}   Target: {row['target']}")
        print(f"   Upside: {row['upside_pct']}%   Risk: {row['risk_pct']}%   RR: {row['rr']}   Horizon: {row['horizon']}")
        print(f"   RSI: {row['rsi']}   MACD bull: {row['macd_bull']}   Vol ratio: {row['vol_ratio']}   AvgDV: ${row['avg_dv_m']}M")
        print(f"   Perf 20d: {row['perf_20d']}%   60d: {row['perf_60d']}%   120d: {row['perf_120d']}%   Base range: {row['base_range']}%")

    print(f"\n{'='*72}")
    print("Legend:")
    print("  BREAKOUT       = clearing 20d high             -> buy on breakout")
    print("  VCP            = Minervini volatility contraction breakout")
    print("  SHORT_SQUEEZE  = >15% short interest + bullish momentum")
    print("  STAGE_2        = Weinstein long-base breakout (rare, high conviction)")
    print("  RR             = reward/risk ratio (>1.5 good, >2.5 excellent)")
    print(f"{'='*72}\n")




# =============================================================
# COMPANY NAMES
# =============================================================
COMPANY_NAME_CACHE = "company_names.json"

def load_company_names():
    try:
        with open(COMPANY_NAME_CACHE, "r", encoding="utf-8") as f:
            return json.load(f)
    except FileNotFoundError:
        return {}

def save_company_names(cache):
    try:
        with open(COMPANY_NAME_CACHE, "w", encoding="utf-8") as f:
            json.dump(cache, f, indent=2, ensure_ascii=False)
    except Exception:
        pass

def get_company_name(ticker, cache):
    if ticker in cache:
        return cache[ticker]
    try:
        with suppress_output():
            info = yf.Ticker(ticker).info
        name = info.get("shortName") or info.get("longName") or ticker
        # Shorten common suffixes for cleaner display
        for suffix in [" Inc.", " Inc", " Corp.", " Corp", " Ltd.", " Ltd",
                       " Holdings", " Group", " Co.", " Co", " plc", " AG", " SE"]:
            if name.endswith(suffix):
                name = name[:-len(suffix)].strip()
                break
        cache[ticker] = name
    except Exception:
        cache[ticker] = ticker
    return cache[ticker]


# =============================================================
# TELEGRAM
# =============================================================
def send_telegram(text):
    """Send a message via Telegram Bot API."""
    if not TELEGRAM_ENABLED:
        return
    if not TELEGRAM_TOKEN or not TELEGRAM_CHAT_ID:
        print("Telegram: Token/Chat-ID not configured, skipping.")
        return
    try:
        import urllib.request
        url  = f"https://api.telegram.org/bot{TELEGRAM_TOKEN}/sendMessage"
        data = json.dumps({
            "chat_id":    TELEGRAM_CHAT_ID,
            "text":       text,
            "parse_mode": "HTML",
        }).encode("utf-8")
        req = urllib.request.Request(url, data=data,
              headers={"Content-Type": "application/json"})
        urllib.request.urlopen(req, timeout=10)
        print("Telegram: Message sent.")
    except Exception as e:
        print(f"Telegram error: {e}")


def escape_md(text):
    """Escape special chars for Telegram HTML mode."""
    text = str(text)
    text = text.replace("&", "&amp;")
    text = text.replace("<", "&lt;")
    text = text.replace(">", "&gt;")
    return text
def get_no_signal_message(market_regime):
    import random
    from datetime import datetime
    mode = market_regime.get("mode", "UNKNOWN")
    date_str = datetime.now().strftime("%d. %B %H:%M Uhr")

    msgs = [
        "Heute habe ich keine Signale für euch, mächtige Investoren. Der Markt schweigt.",
        "Kein Signal heute. Manchmal ist Nichtstun die beste Investition.",
        "Der Scanner hat gesprochen: heute bleibt das Pulver trocken.",
        "Keine Setups heute. Vielleicht ist das Universum der Meinung, ihr habt genug riskiert.",
        "Heute: null Signale. Euer Kontostand dankt es euch möglicherweise.",
        "Stille an der Front. Kein Trade ist auch eine Position.",
        "Heute schlafen die Breakouts. Morgen erwachen sie wieder.",
        "Der Markt flüstert heute nichts. Ich höre trotzdem zu.",
        "Keine Kandidaten heute. Qualität vor Quantität — das ist ApexScan-Philosophie.",
        "Ruhige Nacht an den Märkten. Genießt euren Schlaf, Investoren.",
        "Heute kein Signal. Manchmal ist der beste Trade der, den man nicht macht.",
        "Scanner läuft sauber — der Markt liefert heute einfach nichts Würdiges.",
        "Kein Ausbruch heute. Der Markt testet eure Geduld. Besteht den Test.",
        "Heute: Funkstille. Der nächste Breakout wartet bereits in den Startlöchern.",
        "Keine Signale. Die Aktien brauchen heute eine Pause. Ihr auch.",
        "ApexScan hat alles geprüft und für zu riskant befunden. Spart euer Geld.",
        "Nichts heute. Aber morgen? Vielleicht. Wahrscheinlich. Eventuell.",
        "Der Scanner ruht. Nicht weil er müde ist, sondern weil der Markt es verdient.",
    ]

    text = random.choice(msgs)
    summary = escape_md(market_regime.get("summary", ""))
    macro_line = ""
    try:
        from apex_macro import macro_telegram_line
        macro_line = macro_telegram_line()
    except Exception:
        pass
    macro_suffix = ("\n" + macro_line) if macro_line else ""
    return (
        "\U0001f4a4 <b>ApexScan</b> · " + date_str + "\n\n"
        + escape_md(text) + "\n\n"
        + "<i>" + summary + "</i>" + macro_suffix
    )

def build_telegram_message(candidates, market_regime):
    from datetime import datetime
    now      = datetime.now()
    date_str = escape_md(now.strftime("%d. %B · %H:%M"))
    mode     = escape_md(market_regime.get("mode", "UNKNOWN"))
    icon     = "\U0001f7e2" if market_regime.get("risk_on") else "\U0001f534"
    NL       = "\n"
    name_cache = load_company_names()

    # Catalyst flags (mirror dashboard catBadges)
    def _cat_flags(c):
        f = []
        if c.get("cat_pocket_pivot"):                 f.append("⚡ Pivot")     # lightning
        if c.get("cat_earnings_beat"):                f.append("\U0001f4c8 Beat")  # chart-up
        if (c.get("cat_analyst_upside") or 0) > 15:   f.append("\U0001f3af Analyst")  # dart
        if (c.get("cat_short_pct") or 0) > 15:        f.append("\U0001f525 Squeeze")  # fire
        if c.get("cat_earnings_blackout"):            f.append("⚠ Earnings")  # warning
        return "  ".join(f)

    # Group by setup, preserve score order
    groups = {"STAGE_2": [], "VCP": [], "SHORT_SQUEEZE": [], "BREAKOUT": [], "MEAN_REVERSION": []}
    for c in candidates:
        key = c.get("setup", "")
        if key in groups:
            groups[key].append(c)

    setup_cfg = [
        ("STAGE_2",        "\U0001f680", "Stage-2 Breakout"),   # rocket emoji — rare/big
        ("VCP",            "\U0001f539", "VCP Breakout"),        # blue diamond — quality
        ("SHORT_SQUEEZE",  "\U0001f525", "Short Squeeze"),       # fire — momentum
        ("BREAKOUT",       "\U0001f535", "Breakout"),            # blue circle
        ("MEAN_REVERSION", "\U0001f7e2", "Dip / Mean-Reversion"),# green circle
    ]

    lines = [icon + " <b>ApexScan · " + date_str + " · " + mode + "</b>"]
    try:
        from apex_macro import macro_telegram_line
        macro_line = macro_telegram_line()
        if macro_line:
            lines.append(macro_line)
    except Exception:
        pass

    for key, sicon, label in setup_cfg:
        items = groups[key]
        if not items:
            continue

        # Setup header
        lines.append("\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500")
        lines.append(sicon + " <b>" + label + "</b>")

        for c in items:
            name    = get_company_name(c["ticker"], name_cache)
            ticker  = escape_md(c["ticker"])
            cname   = escape_md(name)
            price   = escape_md(str(c["price"]))
            target  = escape_md(str(c["target"]))
            upside  = escape_md(str(c["upside_pct"]))
            rr      = escape_md(str(c["rr"]))
            horizon = escape_md(c["horizon"].replace("weeks","Wo.").replace("week","Wo."))
            buy     = escape_md(str(c["buy_above"]))
            stop    = escape_md(str(c["stop"]))
            rsi     = escape_md(str(c["rsi"]))
            score   = escape_md(str(c["score"]))

            lines.append("\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500")
            lines.append("<b>" + ticker + " · " + cname + "</b>")
            _flags = _cat_flags(c)
            if _flags:
                lines.append(_flags)
            lines.append("$" + price + " \u2192 $" + target + "  \u2b06 <b>+" + upside + "%</b>")
            lines.append("RR " + rr + "  ·  Entry $" + buy + "  ·  Stop $" + stop)
            lines.append("RSI " + rsi + "  ·  " + horizon + "  ·  Score " + score)

    lines.append("\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500")
    save_company_names(name_cache)
    return NL.join(lines)


# =============================================================
# SIGNAL EXPORT
# =============================================================
def save_signals(candidates):
    """Appends new signals to apex_signals.json (no duplicates)."""
    from datetime import datetime
    today = datetime.now().strftime("%Y-%m-%d")
    signals_file = "apex_signals.json"
    try:
        with open(signals_file, "r", encoding="utf-8") as f:
            existing = json.load(f)
    except FileNotFoundError:
        existing = []

    # Block same ticker if seen in last DUPLICATE_WINDOW_DAYS days
    today_dt = datetime.strptime(today, "%Y-%m-%d")
    recent_tickers = {
        r["ticker"] for r in existing
        if abs((today_dt - datetime.strptime(r["date"], "%Y-%m-%d")).days) <= DUPLICATE_WINDOW_DAYS
    }

    existing_keys = {(r["date"], r["ticker"]) for r in existing}
    new_entries = []
    skipped_recent = []
    for c in candidates:
        if (today, c["ticker"]) in existing_keys:
            continue
        if c["ticker"] in recent_tickers:
            skipped_recent.append(c["ticker"])
            continue
        entry = dict(c)
        entry["date"] = today
        new_entries.append(entry)

    if skipped_recent:
        print(f"  Skipped (seen in last 5 days): {', '.join(skipped_recent)}")

    existing.extend(new_entries)
    with open(signals_file, "w", encoding="utf-8") as f:
        json.dump(clean_nan_for_json(existing), f, indent=2, ensure_ascii=False)
    print(f"Signals saved: {len(new_entries)} new -> {signals_file}  (total: {len(existing)})")


# =============================================================
# MAIN
# =============================================================
def main():
    # Sync with GitHub before scan to avoid duplicate signals
    import subprocess, os
    if os.path.exists(".git"):
        try:
            subprocess.run(["git", "pull", "origin", "master"],
                           capture_output=True, check=True)
            print("Git: Synced with GitHub.")
        except subprocess.CalledProcessError:
            print("Git: Pull failed or no remote – continuing anyway.")

    # Load tickers from both markets
    us_tickers = clean_universe(load_tickers(US_TICKER_FILE))
    eu_tickers = clean_universe(load_tickers(EU_TICKER_FILE))
    all_tickers = unique_keep_order(us_tickers + eu_tickers)

    if not all_tickers:
        print("No tickers loaded. Check us_tickers.txt and eu_tickers.txt")
        return

    print(f"Tickers loaded: {len(us_tickers)} US  +  {len(eu_tickers)} EU  =  {len(all_tickers)} total")

    market_regime = get_market_regime()
    save_market_regime(market_regime)
    print(f"Market regime : {market_regime['summary']}\n")

    candidates, debug = run_scan(all_tickers, market_regime)

    print(f"\nCandidates before sector enrichment: {len(candidates)}")
    print("Debug summary:")
    for k, v in debug.most_common(12):
        print(f"  {k}: {v}")

    candidates = enrich_sector(candidates)
    candidates = apply_sector_cap(candidates)
    print_signals(candidates)

    # Filter out tickers seen in last DUPLICATE_WINDOW_DAYS days (before Telegram AND before save)
    from datetime import datetime as _dt
    today = _dt.now().strftime("%Y-%m-%d")
    today_dt = _dt.strptime(today, "%Y-%m-%d")
    try:
        with open("apex_signals.json", "r", encoding="utf-8") as f:
            _existing = json.load(f)
    except FileNotFoundError:
        _existing = []
    # Combine git-tracked apex_signals.json AND local signal_memory.json
    # The local memory survives git-pull failures (fixes ENPH-style duplicates).
    recent_from_git = {
        r["ticker"] for r in _existing
        if abs((today_dt - _dt.strptime(r["date"], "%Y-%m-%d")).days) <= DUPLICATE_WINDOW_DAYS
        and r.get("relax_level", 0) == 0
    }
    recent_local = {t for t in load_signal_memory()
                    if signal_in_window(t, today, DUPLICATE_WINDOW_DAYS)}
    recent_tickers = recent_from_git | recent_local
    deduped = [c for c in candidates if c["ticker"] not in recent_tickers]
    skipped = [c["ticker"] for c in candidates if c["ticker"] in recent_tickers]
    if skipped:
        print(f"  Duplicate filter: {', '.join(skipped)} skipped (seen in last {DUPLICATE_WINDOW_DAYS} days).")
    candidates = deduped

    # Persist new signals to local memory BEFORE save_signals so future runs see them
    if candidates:
        update_signal_memory([c["ticker"] for c in candidates], today)

    save_signals(candidates)

    # Send Telegram notification — quality (score-based) → top 2 by score
    if candidates:
        # 2026-05-22: SCORE-based eligibility, NOT relax-based.
        # Backtest (120d, 810 tickers, n=100): relax=1 signals scored WR 56% /
        # PF 2.14 vs strict relax=0 WR 41% / PF 1.61. The relax LEVEL is not
        # predictive of quality — the SCORE is (all score-buckets >=50% WR).
        # The old relax==0-only gate starved Telegram (0 signals for days once
        # REVERSAL was disabled). Now gate purely on setup-score + RR/upside,
        # regardless of relax level.
        def _min_score_for(c):
            return TG_MIN_SCORE.get(c.get("setup", ""), TG_MIN_SCORE_DEFAULT)

        quality = [c for c in candidates if
                   c.get("rr", 0)         >= TG_MIN_RR and
                   c.get("upside_pct", 0) >= TG_MIN_UPSIDE and
                   c.get("score", 0)      >= _min_score_for(c)]

        n_filtered = len(candidates) - len(quality)
        if n_filtered:
            print(f"  Telegram filter: {n_filtered} signal(s) below quality threshold excluded.")

        if quality:
            top2 = sorted(quality, key=lambda x: x.get("score", 0), reverse=True)[:2]
            n_relaxed = sum(1 for c in top2 if c.get("relax_level", 0) > 0)
            if n_relaxed:
                print(f"  Note: {n_relaxed}/{len(top2)} pushed signal(s) are relax>0 (score-eligible).")
            msg = build_telegram_message(top2, market_regime)
            send_telegram(msg)
        else:
            print("  Note: No candidate passed quality threshold — sending no-signal message.")
            send_telegram(get_no_signal_message(market_regime))
    else:
        send_telegram(get_no_signal_message(market_regime))


if __name__ == "__main__":
    main()