import sys
import io
import json
import math
import os
import contextlib
import warnings
from collections import Counter

import pandas as pd
import yfinance as yf
from tqdm import tqdm

# Phase B: yfinance fundamental catalysts (earnings, short, analyst)
try:
    from apex_catalysts import (
        get_catalyst_data,
        derive_catalyst_signals,
        score_delta_for_catalyst_signals,
    )
    CATALYSTS_AVAILABLE = True
except ImportError:
    CATALYSTS_AVAILABLE = False

# =============================================================
# SETTINGS
# =============================================================
US_TICKER_FILE  = "us_tickers.txt"
EU_TICKER_FILE  = "eu_tickers.txt"       # create this file with EU tickers
SECTOR_CACHE    = "sector_cache.json"

TOP_RESULTS     = 20
BATCH_SIZE      = 80
HISTORY_PERIOD  = "18mo"

MIN_DATA_DAYS       = 100
MIN_PRICE           = 2
MIN_AVG_VOLUME      = 50_000
MIN_DOLLAR_VOLUME   = 500_000

# Adaptive relaxation: if fewer than MIN_SIGNALS pass, thresholds loosen
MIN_SIGNALS         = 1
MAX_SIGNALS         = 10
DUPLICATE_WINDOW_DAYS = 3

# Quality filter for Telegram top-2 (setup-specific, data-driven)
TG_MIN_RR      = 2.0
TG_MIN_UPSIDE  = 8.0
TG_MIN_SCORE   = {"BREAKOUT": 70, "REVERSAL": 45}  # BO@70 = 67% WR, REV@45 = 42% WR
TG_MIN_SCORE_DEFAULT = 70

# Hard scan-level score gate per setup (drops candidates below threshold entirely)
SCAN_MIN_SCORE = {"BREAKOUT": 70, "REVERSAL": 50}  # BO@70 = 63% WR / PF 2.09 (Phase A data)

# Ticker winrate file (generated by apex_backtest_v2.py)
TICKER_WINRATE_FILE = "ticker_winrate.json"

warnings.filterwarnings("ignore")

# =============================================================
# TELEGRAM CONFIG
# =============================================================
TELEGRAM_TOKEN   = os.environ.get("TELEGRAM_TOKEN", "8335991939:AAHzZPTygh6O7phgz24sXXL5PGEEVRc2d5g")   # set env var or fill here
TELEGRAM_CHAT_ID = os.environ.get("TELEGRAM_CHAT_ID", "-1003557116590")  # set env var or fill here
TELEGRAM_ENABLED = True                     # set False to disable


# =============================================================
# UTILS
# =============================================================
@contextlib.contextmanager
def suppress_output():
    old_out, old_err = sys.stdout, sys.stderr
    try:
        sys.stdout = io.StringIO()
        sys.stderr = io.StringIO()
        yield
    finally:
        sys.stdout = old_out
        sys.stderr = old_err


def normalize_ticker(ticker: str) -> str:
    return str(ticker).strip().upper().replace(".", "-")


def unique_keep_order(items):
    seen, out = set(), []
    for x in items:
        if x and x not in seen:
            seen.add(x)
            out.append(x)
    return out


def load_tickers(file_path):
    try:
        with open(file_path, "r", encoding="utf-8") as f:
            tickers = [normalize_ticker(line) for line in f if line.strip()]
        return unique_keep_order(tickers)
    except FileNotFoundError:
        return []


# Known dead tickers to skip (saves download time)
DEAD_TICKERS = {
    "TWTR", "FB", "SIVB", "FRC", "YHOO", "GGP", "CELG", "RTN", "STI",
    "VIAB", "APC", "RHT", "LLL", "AGN", "ETFC", "NBL", "ALXN", "BIIB",
    "ATVI", "XLNX", "DISH", "INFO", "DXC", "ABMD", "NKTR", "DWDP",
    "BHF", "DRE", "ARNC", "COTY", "FBHS", "WFM", "BBBY", "LEH",
    "FNM", "FRE", "CFC", "WB", "JDSU", "NOVL", "GENZ", "MFE", "EK",
    "SGP", "BCR", "SPLS", "RAI", "BHI", "SNI", "MON", "DPS", "TWX",
    "CA", "WYN", "XL", "ANDV", "SRCL", "AET", "COL", "SCG", "LLL",
    "PCLN", "ESRX", "NAVI", "GMCR", "ADS", "KORS", "TSS", "JEF",
}

# Tickers that consistently underperform in our backtest (2+ trades, WR ≤25%,
# negative cumulative PnL). Data-driven blacklist from apex_backtest_results.json
# (2024-01 to 2026-04 window). Revert by emptying this set.
BAD_PERFORMERS = {
    "VRSK", "ALGN", "DDOG", "OWL", "APTV", "FICO", "CMC", "KSS",
    "IFF", "GT", "FSLR", "MKTX", "AFG", "JKHY", "J", "KMI",
}


def clean_universe(tickers):
    cleaned = []
    for t in tickers:
        if not t or len(t) > 8:
            continue
        if "^" in t or "/" in t or "=" in t:
            continue
        if t in DEAD_TICKERS or t in BAD_PERFORMERS:
            continue
        cleaned.append(t)
    return unique_keep_order(cleaned)


def chunked(lst, size):
    for i in range(0, len(lst), size):
        yield lst[i:i + size]


def safe_float(x, default=0.0):
    try:
        return default if pd.isna(x) else float(x)
    except Exception:
        return default


def percent_change(current, past):
    if pd.isna(current) or pd.isna(past) or past == 0:
        return None
    return ((float(current) / float(past)) - 1) * 100


# =============================================================
# INDICATORS
# =============================================================
def rsi_wilder(series, period=14):
    """Wilder's smoothed RSI (more accurate than simple rolling mean)."""
    delta = series.diff()
    gain  = delta.clip(lower=0)
    loss  = -delta.clip(upper=0)
    # First value: simple mean
    avg_gain = gain.ewm(alpha=1/period, min_periods=period, adjust=False).mean()
    avg_loss = loss.ewm(alpha=1/period, min_periods=period, adjust=False).mean()
    rs = avg_gain / avg_loss.replace(0, float("nan"))
    return 100 - (100 / (1 + rs))


def macd(series, fast=12, slow=26, signal=9):
    ema_fast   = series.ewm(span=fast, adjust=False).mean()
    ema_slow   = series.ewm(span=slow, adjust=False).mean()
    macd_line  = ema_fast - ema_slow
    signal_line = macd_line.ewm(span=signal, adjust=False).mean()
    histogram  = macd_line - signal_line
    return macd_line, signal_line, histogram


def atr(df, period=14):
    hl  = df["High"] - df["Low"]
    hc  = (df["High"] - df["Close"].shift(1)).abs()
    lc  = (df["Low"]  - df["Close"].shift(1)).abs()
    tr  = pd.concat([hl, hc, lc], axis=1).max(axis=1)
    return tr.ewm(alpha=1/period, min_periods=period, adjust=False).mean()


# =============================================================
# CATALYSTS (technical, computed from OHLCV — no API needed)
# =============================================================
def compute_technical_catalysts(df, atr14_now, vol_ratio):
    """
    Detects 4 evidence-based price-jump triggers from chart data:
      - Pocket Pivot (Morales/IBD): up-day where today's vol > max down-vol last 10d
      - Volume Climax: vol_ratio >= 3.0 today
      - Up-Gap: open today >2% above prev close
      - VCP (Minervini): ATR contracting >=30% over last 4 weeks
    Returns dict of signals + magnitudes.
    """
    out = {
        "pocket_pivot_recent": False,  # in last 5 trading days
        "volume_climax": False,
        "up_gap_pct": 0.0,
        "gap_signal": False,
        "vcp_strength": 0.0,    # 0..1
        "vcp_signal": False,
    }
    if df is None or len(df) < 21:
        return out

    closes = df["Close"].values
    vols   = df["Volume"].values
    opens  = df["Open"].values
    n = len(closes)

    # --- Pocket Pivot in last 5 days ---
    for i in range(1, 6):
        idx = n - i
        if idx < 11:
            break
        if closes[idx] <= closes[idx-1]:
            continue  # need up-day
        sub_close      = closes[idx-10:idx]
        sub_vol        = vols[idx-10:idx]
        sub_close_prev = closes[idx-11:idx-1]
        down_mask = sub_close < sub_close_prev
        if down_mask.any():
            max_down_vol = sub_vol[down_mask].max()
            if vols[idx] > max_down_vol:
                out["pocket_pivot_recent"] = True
                break

    # --- Volume Climax (today) ---
    out["volume_climax"] = vol_ratio >= 3.0

    # --- Up-Gap (today) ---
    if n >= 2 and closes[-2] > 0:
        out["up_gap_pct"] = (opens[-1] - closes[-2]) / closes[-2] * 100
        out["gap_signal"] = out["up_gap_pct"] > 2.0

    # --- VCP: ATR contraction over 4 weeks ---
    if "ATR14" in df.columns and n >= 21:
        atr_old = df["ATR14"].iloc[-21]
        if not pd.isna(atr_old) and atr_old > 0 and atr14_now > 0:
            contraction = 1 - (atr14_now / atr_old)
            out["vcp_strength"] = max(0.0, min(contraction, 1.0))
            out["vcp_signal"] = out["vcp_strength"] >= 0.30

    return out


# =============================================================
# DOWNLOAD
# =============================================================
def safe_download_single(ticker, period="1y"):
    try:
        with suppress_output():
            df = yf.download(ticker, period=period, auto_adjust=True,
                             progress=False, threads=False)
        return df.copy() if df is not None and not df.empty else None
    except Exception:
        return None


def extract_ticker_frame(raw_data, ticker):
    try:
        if raw_data is None or raw_data.empty:
            return None
        if isinstance(raw_data.columns, pd.MultiIndex):
            lvl0 = raw_data.columns.get_level_values(0).tolist()
            lvl1 = raw_data.columns.get_level_values(1).tolist()
            if ticker in lvl0:
                df = raw_data[ticker].copy()
            elif ticker in lvl1:
                df = raw_data.xs(ticker, axis=1, level=1).copy()
            else:
                return None
        else:
            df = raw_data.copy()

        required = ["Open", "High", "Low", "Close", "Volume"]
        if any(c not in df.columns for c in required):
            return None
        df = df[required].dropna().copy()
        return df if len(df) >= 30 else None
    except Exception:
        return None


# =============================================================
# MARKET REGIME
# =============================================================
def get_market_regime():
    # Download 2y to ensure enough data for MA200
    spy = safe_download_single("SPY", "2y")
    qqq = safe_download_single("QQQ", "2y")

    if spy is None or qqq is None:
        return {"risk_on": False, "mode": "UNKNOWN",
                "summary": "Market filter unavailable -> defaulting to RISK-OFF"}

    def regime(df):
        # Squeeze handles MultiIndex columns from yfinance
        c = df["Close"].squeeze() if hasattr(df["Close"], "squeeze") else df["Close"]
        if isinstance(c, pd.DataFrame):
            c = c.iloc[:, 0]
        c = c.dropna()
        if len(c) < 50:
            return "UNKNOWN"

        ma20  = c.rolling(20).mean()
        ma50  = c.rolling(50).mean()
        ma200 = c.rolling(200).mean() if len(c) >= 200 else None

        lc  = safe_float(c.iloc[-1])
        l20 = safe_float(ma20.iloc[-1])
        l50 = safe_float(ma50.iloc[-1])

        # Only use MA200 if we have enough data and it's not NaN
        if ma200 is not None:
            l200_val = ma200.iloc[-1]
            l200 = safe_float(l200_val) if not pd.isna(l200_val) else None
        else:
            l200 = None

        if l200 is not None:
            if lc > l20 > l50 > l200:   return "STRONG"
            if lc > l50 and l50 > l200: return "OK"
        else:
            # No MA200 — use MA50 only
            if lc > l20 > l50: return "STRONG"
            if lc > l50:       return "OK"
        return "WEAK"

    sr, qr = regime(spy), regime(qqq)
    risk_on = sr in {"STRONG", "OK"} and qr in {"STRONG", "OK"}

    if sr == "STRONG" and qr == "STRONG": mode = "BULLISH"
    elif risk_on:                          mode = "MIXED"
    else:                                  mode = "BEARISH"

    # SPY 20-day performance for relative strength calculation
    spy_close = spy["Close"].squeeze().dropna()
    spy_perf_20 = 0.0
    if len(spy_close) >= 21:
        spy_perf_20 = float((spy_close.iloc[-1] / spy_close.iloc[-21] - 1) * 100)

    # Sector ETF momentum (20d performance)
    sector_etfs = {
        "Energy":            "XLE",
        "Technology":        "XLK",
        "Healthcare":        "XLV",
        "Financials":        "XLF",
        "Industrials":       "XLI",
        "Consumer Defensive":"XLP",
        "Consumer Cyclical": "XLY",
        "Basic Materials":   "XLB",
        "Utilities":         "XLU",
        "Real Estate":       "XLRE",
        "Communication":     "XLC",
    }
    sector_momentum = {}
    try:
        etf_symbols = list(sector_etfs.values())
        etf_batch = yf.download(" ".join(etf_symbols), period="3mo",
                                group_by="ticker", auto_adjust=True,
                                progress=False, threads=True)
        for sector, etf in sector_etfs.items():
            try:
                if len(etf_symbols) == 1:
                    c = etf_batch["Close"].squeeze().dropna()
                else:
                    c = etf_batch[etf]["Close"].squeeze().dropna()
                if len(c) >= 21:
                    sector_momentum[sector] = round(float((c.iloc[-1] / c.iloc[-21] - 1) * 100), 2)
                else:
                    sector_momentum[sector] = 0.0
            except Exception:
                sector_momentum[sector] = 0.0
    except Exception:
        for sector in sector_etfs:
            sector_momentum[sector] = 0.0

    return {"risk_on": risk_on, "mode": mode,
            "summary": f"SPY={sr} | QQQ={qr} | Market={mode}",
            "spy_perf_20": spy_perf_20,
            "sector_momentum": sector_momentum}



def save_market_regime(market_regime):
    from datetime import datetime
    data = {
        "mode":    market_regime.get("mode", "UNKNOWN"),
        "risk_on": market_regime.get("risk_on", False),
        "summary": market_regime.get("summary", ""),
        "updated": datetime.now().strftime("%Y-%m-%d %H:%M")
    }
    with open("apex_market.json", "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2)


# =============================================================
# TARGET CALCULATION
# =============================================================
def find_target(df, buy_above, atr14, setup, risk_pct):
    """
    Finds a realistic price target using multiple methods:
    1. Previous swing highs (historical resistance)
    2. Fibonacci 1.272 / 1.618 extensions from last swing
    3. Round price levels (psychological resistance)
    4. ATH + buffer if near all-time high
    5. Fallback: RR-based with variable multiplier per setup

    Picks the nearest valid candidate above buy_above (min 4%, max 25% upside).
    """
    MIN_UPSIDE = 4.0    # minimum target distance %
    MAX_UPSIDE = 25.0   # maximum before considered unrealistic
    RR_FALLBACK = {"BREAKOUT": 2.0, "PRE-ROCKET": 2.5, "POSITION": 3.0}

    highs  = df["High"].values
    lows   = df["Low"].values
    n      = len(highs)

    candidates = []

    # --- Method 1: Swing highs (last 252 bars) ---
    SWING_W = 3
    lookback  = min(252, n - 1)
    start_idx = max(SWING_W, n - lookback)
    for i in range(start_idx, n - SWING_W):
        h = highs[i]
        if h <= buy_above:
            continue
        left  = highs[max(0, i - SWING_W) : i]
        right = highs[i + 1 : i + SWING_W + 1]
        if len(left) and len(right) and h > max(left) and h > max(right):
            candidates.append(round(h, 2))

    # --- Method 2: Fibonacci extensions ---
    # Find last significant swing low and swing high before buy_above
    recent = min(60, n - 1)
    swing_low  = float(min(lows[-recent:]))
    swing_high = float(max(highs[-recent:]))

    if swing_high > swing_low:
        move = swing_high - swing_low
        fib_1272 = round(swing_low + move * 1.272, 2)
        fib_1618 = round(swing_low + move * 1.618, 2)
        if fib_1272 > buy_above:
            candidates.append(fib_1272)
        if fib_1618 > buy_above:
            candidates.append(fib_1618)

    # --- Method 3: Round price levels ---
    # Find the next round numbers above buy_above
    def next_round_levels(price, above):
        levels = []
        # Determine magnitude of rounding
        if above > 500:   steps = [10, 25, 50, 100]
        elif above > 100: steps = [5, 10, 25, 50]
        elif above > 50:  steps = [2.5, 5, 10, 25]
        elif above > 10:  steps = [1, 2.5, 5, 10]
        else:             steps = [0.5, 1, 2.5, 5]
        for step in steps:
            rounded = math.ceil(above / step) * step
            # Add a few levels
            for i in range(5):
                lvl = round(rounded + i * step, 2)
                if lvl > above:
                    levels.append(lvl)
        return levels

    round_levels = next_round_levels(buy_above, buy_above)
    candidates.extend(round_levels)

    # --- Method 4: ATH + small buffer if near all-time high ---
    ath = float(df["High"].max())
    if ath > buy_above:
        candidates.append(round(ath, 2))
        candidates.append(round(ath * 1.05, 2))
        candidates.append(round(ath * 1.10, 2))

    # --- Step 5: Enforce minimum target = 2x ATR from entry ---
    # This ensures targets are not trivially close (avoids <5% upside)
    min_target_mult = {"BREAKOUT": 2.5, "PRE-ROCKET": 3.0, "POSITION": 4.0}
    atr_min_target  = buy_above + (atr14 * min_target_mult.get(setup, 2.5))
    atr_min_upside  = (atr_min_target / buy_above - 1) * 100

    # Use ATR minimum as floor for MIN_UPSIDE
    effective_min = max(MIN_UPSIDE, atr_min_upside)

    candidates = sorted(set(candidates))
    target = None
    for c in candidates:
        upside = (c / buy_above - 1) * 100
        if effective_min <= upside <= MAX_UPSIDE:
            target = c
            break

    # --- Fallback: ATR-based minimum target ---
    if target is None:
        rr_mult = RR_FALLBACK.get(setup, 2.0)
        rr_target = round(buy_above * (1 + (risk_pct * rr_mult) / 100), 2)
        # Take the larger of RR-based and ATR-based target
        target = max(rr_target, round(atr_min_target, 2))

    return target


# =============================================================
# TICKER WINRATE
# =============================================================
def load_ticker_winrate():
    try:
        with open(TICKER_WINRATE_FILE, "r", encoding="utf-8") as f:
            return json.load(f)
    except FileNotFoundError:
        return {}

TICKER_WINRATE = load_ticker_winrate()

# =============================================================
# CORE SCANNER
# =============================================================
def scan_ticker(ticker, data, market_regime, debug, sector_cache, relax=0):
    """
    relax=0  -> strict filters
    relax=1  -> slightly relaxed (fallback pass 1)
    relax=2  -> broad sweep (fallback pass 2, guarantees some output)
    """
    try:
        if data is None or data.empty:
            debug["empty_data"] += 1
            return None
        if len(data) < MIN_DATA_DAYS:
            debug["too_short"] += 1
            return None

        df = data.copy()
        df["MA20"]   = df["Close"].rolling(20).mean()
        df["MA50"]   = df["Close"].rolling(50).mean()
        df["MA150"]  = df["Close"].rolling(150).mean()
        df["VOL20"]  = df["Volume"].rolling(20).mean()
        df["RSI14"]  = rsi_wilder(df["Close"], 14)
        df["ATR14"]  = atr(df, 14)

        ml, sl, hist = macd(df["Close"])
        df["MACD"]      = ml
        df["MACD_SIG"]  = sl
        df["MACD_HIST"] = hist

        df = df.dropna(subset=["MA20","MA50","VOL20","RSI14","ATR14","MACD"]).copy()
        if len(df) < 30:
            debug["too_short_after_ind"] += 1
            return None

        l = df.iloc[-1]
        prev = df.iloc[-2]

        close   = safe_float(l["Close"])
        high    = safe_float(l["High"])
        vol     = safe_float(l["Volume"])
        vol20   = safe_float(l["VOL20"])
        ma20    = safe_float(l["MA20"])
        ma50    = safe_float(l["MA50"])
        ma150   = safe_float(l["MA150"])
        rsi14   = safe_float(l["RSI14"])
        atr14   = safe_float(l["ATR14"])
        macd_h  = safe_float(l["MACD_HIST"])
        macd_h_prev = safe_float(prev["MACD_HIST"])

        # ---- Basic filters ----
        if close < MIN_PRICE:
            debug["price_too_low"] += 1
            return None
        avg_dv = close * vol20
        if vol20 < MIN_AVG_VOLUME or avg_dv < MIN_DOLLAR_VOLUME:
            debug["volume_too_low"] += 1
            return None

        # ---- Lookback windows ----
        prev_20_high = safe_float(df["High"].iloc[-21:-1].max())
        prev_10_high = safe_float(df["High"].iloc[-11:-1].max())
        low_10       = safe_float(df["Low"].iloc[-10:].min())
        high_10      = safe_float(df["High"].iloc[-10:].max())
        high_52w     = safe_float(df["High"].iloc[-252:].max()) if len(df) >= 252 else safe_float(df["High"].max())
        pct_from_52w = ((close - high_52w) / high_52w * 100) if high_52w > 0 else 0

        perf_20  = percent_change(close, df["Close"].iloc[-21])
        perf_60  = percent_change(close, df["Close"].iloc[-61]) if len(df) >= 61 else None
        perf_120 = percent_change(close, df["Close"].iloc[-121]) if len(df) >= 121 else None

        if perf_20 is None:
            debug["perf_invalid"] += 1
            return None
        if perf_60  is None: perf_60  = perf_20
        if perf_120 is None: perf_120 = perf_60

        vol_ratio  = vol / vol20 if vol20 > 0 else 0
        base_range = percent_change(high_10, low_10)
        atr_pct    = (atr14 / close) * 100 if close > 0 else 0

        if base_range is None:
            debug["base_invalid"] += 1
            return None

        # ---- Technical catalysts (Phase A: pocket pivot, vol climax, gap, VCP) ----
        catalysts = compute_technical_catalysts(df, atr14, vol_ratio)

        # ---- Fundamental catalysts (Phase B: yfinance earnings/short/analyst) ----
        catalyst_signals = None
        if CATALYSTS_AVAILABLE:
            try:
                _raw = get_catalyst_data(ticker)
                catalyst_signals = derive_catalyst_signals(_raw)
            except Exception:
                catalyst_signals = None

        # ---- Indicator signals ----
        macd_bull  = macd_h > 0 and macd_h > macd_h_prev
        higher_tf  = ma150 > 0 and close >= ma150 * 0.95

        # ---- Per-setup RSI zones (tighter to reduce SL rate) ----
        # BREAKOUT: 45-68 (not overbought), PRE-ROCKET: 40-65, relax widens
        if relax == 0:
            rsi_breakout    = 45 <= rsi14 <= 68
            rsi_prerocket   = 40 <= rsi14 <= 65
            rsi_zone        = rsi_breakout  # default, overridden per setup below
        else:
            rsi_breakout    = 40 <= rsi14 <= 72
            rsi_prerocket   = 38 <= rsi14 <= 72
            rsi_zone        = 38 <= rsi14 <= 75

        # ---- Trend filters (loosen with relax) ----
        if relax == 0:
            trend_ok   = close > ma20 and ma20 > ma50 * 0.99
            near_high  = close >= prev_20_high * 0.93
            base_ok    = base_range <= 8     # tighter: was 22
        elif relax == 1:
            trend_ok   = close > ma50
            near_high  = close >= prev_20_high * 0.88
            base_ok    = base_range <= 15
        else:
            trend_ok   = close > ma150 * 0.90 if ma150 > 0 else close > ma50
            near_high  = close >= prev_20_high * 0.80
            base_ok    = base_range <= 25

        short_near_high = close >= prev_10_high * 0.95
        breakout_touch  = high >= prev_20_high * 0.995
        vol_ok          = vol_ratio >= (0.7 if relax >= 1 else 1.0)
        expansion_vol   = vol_ratio >= 1.1
        momentum_ok     = perf_20 > 0 and perf_60 > 0

        # ---- REVERSAL: check independently before hard exits ----
        # Oversold stock turning up — works best in RISK-OFF markets
        macd_turning    = macd_h > macd_h_prev and macd_h_prev < 0
        not_near_high   = close < prev_20_high * 0.92  # must be clearly below highs
        reversal_setup  = (
            -40 <= pct_from_52w <= -12 and               # 12-40% below 52w high
            25 <= rsi14 <= 48 and                        # oversold zone (wider)
            (macd_turning or (macd_h > macd_h_prev)) and # MACD improving
            vol_ratio >= 1.1 and                         # volume confirmation
            (ma150 == 0 or close >= ma150 * 0.85) and   # allow more below MA150
            perf_20 >= -35 and                           # not in total free fall
            close > MIN_PRICE * 3 and                    # avoid penny stocks
            not_near_high                                # not already near highs
        )

        # ---- Hard exits (skip for REVERSAL) ----
        if not reversal_setup:
            if not trend_ok:   debug["fail_trend"]   += 1; return None
            if not vol_ok:     debug["fail_volume"]   += 1; return None
            if not rsi_zone:   debug["fail_rsi"]      += 1; return None
            if relax == 0 and not momentum_ok: debug["fail_momentum"] += 1; return None
            if relax == 0 and not base_ok:     debug["fail_base"]     += 1; return None
        if atr_pct > 15:   debug["atr_too_high"]  += 1; return None

        # ---- Setup classification ----
        # BREAKOUT: price max 1% below entry (really pressing the high)
        buy_above_preview = prev_20_high * 1.002
        breakout_close    = close >= buy_above_preview * 0.99
        breakout_setup    = breakout_touch and higher_tf and rsi_breakout and breakout_close

        # PRE-ROCKET: DISABLED — low win rate (40%), high SL rate
        pre_rocket_setup  = False

        # POSITION: DISABLED — underperforms in current market
        position_setup    = False

        if not (breakout_setup or pre_rocket_setup or position_setup or reversal_setup):
            debug["fail_setup"] += 1
            return None

        # Market filter: RISK-OFF → only BREAKOUT + REVERSAL allowed
        if not market_regime["risk_on"] and relax == 0:
            if pre_rocket_setup and not breakout_setup and not reversal_setup:
                debug["blocked_market"] += 1
                return None
            if position_setup and not breakout_setup and not reversal_setup:
                debug["blocked_market"] += 1
                return None

        # ---- Entry / Stop / Target ----

        if reversal_setup and not breakout_setup and not pre_rocket_setup and not position_setup:
            # REVERSAL: buy now, stop below recent low, target = 50% Fib retracement
            setup     = "REVERSAL"
            horizon   = "3-8 weeks"
            buy_above = round(close * 1.005, 2)
            action    = f"BUY now at {buy_above:.2f}"   # entry slightly above current price

            # Stop: below 10-day low with ATR buffer
            stop      = round(low_10 - (atr14 * 0.5), 2)
            risk_pct  = (buy_above - stop) / buy_above * 100 if buy_above > 0 else 99

            # Clamp stop
            if risk_pct < 3.0:
                stop     = buy_above * 0.97
                risk_pct = 3.0
            elif risk_pct > 10.0:
                stop     = buy_above - (atr14 * 1.5)
                risk_pct = (buy_above - stop) / buy_above * 100
                if risk_pct > 10.0:
                    debug["risk_too_high"] += 1
                    return None

            # Target: 50% Fibonacci retracement of the fall from 52w high
            fib_target = round(close + (high_52w - close) * 0.50, 2)
            target     = fib_target

        else:
            buy_above = prev_20_high * 1.002

            # Base: 10-day low
            stop_candidate = low_10 * 0.995
            atr_pct_val    = (atr14 / buy_above) * 100 if buy_above > 0 else 5.0
            min_dist_pct   = max(3.0, atr_pct_val * 1.5)
            multiplier     = 1.0 if (position_setup and not breakout_setup) else 1.5
            candidate_dist = ((buy_above - stop_candidate) / buy_above * 100
                              if buy_above > 0 else 99)

            if candidate_dist < min_dist_pct:
                stop = buy_above * (1 - min_dist_pct / 100)
            elif candidate_dist > 6:
                stop = buy_above - (atr14 * multiplier)
            else:
                stop = stop_candidate

            risk_pct = (buy_above - stop) / buy_above * 100 if buy_above > 0 else 99

            # Absolute clamp: [3%, 10%]
            if risk_pct < 3.0:
                stop     = buy_above * 0.97
                risk_pct = 3.0
            elif risk_pct > 10.0:
                debug["risk_too_high"] += 1
                return None

            if breakout_setup:
                setup   = "BREAKOUT"
                horizon = "1-3 weeks"
                action  = f"BUY above {buy_above:.2f}"
            elif position_setup and not breakout_setup:
                setup   = "POSITION"
                horizon = "4-12 weeks"
                action  = f"BUY above {buy_above:.2f} (position)"
            else:
                setup   = "PRE-ROCKET"
                horizon = "2-6 weeks"
                action  = f"WATCH -> BUY above {buy_above:.2f}"

            # Individual target: next swing high above entry, ATR fallback
            target = find_target(df, buy_above, atr14, setup, risk_pct)

        upside_pct = ((target / buy_above) - 1) * 100
        rr = upside_pct / risk_pct if risk_pct > 0 else 0

        min_rr = 1.5 if relax == 0 else 1.2
        if rr < min_rr:
            debug["rr_too_low"] += 1
            return None

        # Minimum upside filter per setup
        min_upside = 10.0 if setup == "REVERSAL" else 8.0
        if upside_pct < min_upside:
            debug["upside_too_low"] = debug.get("upside_too_low", 0) + 1
            return None

        # ---- Score: setup-specific calculation ----
        if reversal_setup and not breakout_setup:
            # REVERSAL score: rewards oversold, deep dip, strong rebound potential
            score = 20.0  # base

            # RSI: lower is better (28-38 sweet spot)
            if 28 <= rsi14 <= 35:   score += 15
            elif 35 < rsi14 <= 42:  score += 10
            elif 42 < rsi14 <= 45:  score += 5

            # MACD histogram turning up from negative = key signal
            macd_turning = macd_h > macd_h_prev and macd_h_prev < 0
            score += 15 if macd_turning else (8 if macd_bull else 0)

            # Volume confirmation
            if vol_ratio >= 1.5:    score += 10
            elif vol_ratio >= 1.3:  score += 7
            elif vol_ratio >= 1.1:  score += 4

            # Depth of dip (perf_20): -10% to -30% is sweet spot
            dip = abs(min(perf_20, 0))
            if 15 <= dip <= 30:    score += 12
            elif 10 <= dip < 15:   score += 8
            elif dip > 30:         score += 5  # too deep, risky

            # Distance from 52w high (pct_from_52w): -15% to -35% ideal
            depth_52w = abs(pct_from_52w) if pct_from_52w < 0 else 0
            if 15 <= depth_52w <= 35: score += 10
            elif 35 < depth_52w <= 40: score += 6

            # RR: big targets reward well
            score += min(rr, 5.0) * 4

            # Upside potential
            if upside_pct >= 20:    score += 10
            elif upside_pct >= 12:  score += 6
            elif upside_pct >= 8:   score += 3

            # No risk-regime bonus for REVERSAL — initial small-sample suggested
            # risk_off edge (+8pp at n=24) but at n=124 the effect dissolved
            # (risk_off 40.3% vs risk_on 39.7%). Removed to avoid Overfit.

            # Phase A catalysts (REVERSAL-relevant subset)
            if catalysts["pocket_pivot_recent"]: score += 5  # institutional accumulation
            if catalysts["volume_climax"]:       score += 5  # selling-climax-confirmation

        else:
            # BREAKOUT score (original logic)
            score = 0.0
            score += 20
            score += 8  if higher_tf else 0
            score += 8  if expansion_vol else (4 if vol_ratio >= 1.0 else 0)
            score += 8  if macd_bull else 0
            score += 6  if 48 <= rsi14 <= 68 else (3 if rsi_zone else 0)
            score += 5  if market_regime["risk_on"] else 0
            score += min(max(perf_20, 0), 20)  * 0.8
            score += min(max(perf_60, 0), 35)  * 0.5
            score += min(max(perf_120, 0), 50) * 0.2
            score += min(vol_ratio, 3.0) * 4
            score += min(rr, 5.0) * 4
            score += 3 if short_near_high else 0

            # Phase A catalysts (BREAKOUT — full set)
            if catalysts["pocket_pivot_recent"]: score += 10  # Morales/IBD: inst. accumulation
            if catalysts["volume_climax"]:       score += 5   # unusual flow / news
            if catalysts["gap_signal"]:          score += 8   # overnight catalyst
            if catalysts["vcp_signal"]:          score += 5   # Minervini pre-breakout

        # Historical winrate bonus (both setups)
        wr_data = TICKER_WINRATE.get(ticker)
        if wr_data and wr_data.get("total", 0) >= 2:
            wr = wr_data["winrate"]
            score += (wr - 50) * 0.2  # +10 for 100% WR, -10 for 0% WR

        # RS and Sector bonuses ONLY for BREAKOUT (mean-reversion REVERSAL bets
        # AGAINST momentum — high RS/Sector mom would penalize valid REVERSAL setups)
        if setup == "BREAKOUT":
            # 1. Relative Strength vs SPY
            spy_perf = market_regime.get("spy_perf_20", 0)
            rs = perf_20 - spy_perf  # positive = outperforming market
            if rs >= 5:    score += 8   # strong outperformer
            elif rs >= 2:  score += 5
            elif rs >= 0:  score += 2
            elif rs < -5:  score -= 5   # significant underperformer
            elif rs < -2:  score -= 2

            # 4. Sector Momentum — sector looked up from cache
            sector_mom = market_regime.get("sector_momentum", {})
            ticker_sector = sector_cache.get(ticker, "Unknown")
            sector_map = {
                "Energy": "Energy", "Technology": "Technology",
                "Healthcare": "Healthcare", "Financial Services": "Financials",
                "Industrials": "Industrials", "Consumer Defensive": "Consumer Defensive",
                "Consumer Cyclical": "Consumer Cyclical", "Basic Materials": "Basic Materials",
                "Utilities": "Utilities", "Real Estate": "Real Estate",
                "Communication Services": "Communication",
            }
            mapped = sector_map.get(ticker_sector, ticker_sector)
            sec_perf = sector_mom.get(mapped, 0)
            if sec_perf >= 5:    score += 6
            elif sec_perf >= 2:  score += 3
            elif sec_perf < -5:  score -= 5
            elif sec_perf < -2:  score -= 2

        # ---- Phase B fundamental catalysts (earnings, short, analyst) ----
        if catalyst_signals is not None:
            score += score_delta_for_catalyst_signals(catalyst_signals, setup)

        # ---- Hard score gate (per setup) ----
        min_score = SCAN_MIN_SCORE.get(setup, 0)
        if score < min_score:
            debug["score_below_gate"] = debug.get("score_below_gate", 0) + 1
            return None

        debug["passed"] += 1

        return {
            "ticker":           ticker,
            "setup":            setup,
            "action":           action,
            "price":            round(close, 2),
            "buy_above":        round(buy_above, 2),
            "stop":             round(stop, 2),
            "target":           round(target, 2),
            "upside_pct":       round(upside_pct, 1),
            "risk_pct":         round(risk_pct, 1),
            "rr":               round(rr, 2),
            "horizon":          horizon,
            "rsi":              round(rsi14, 1),
            "macd_bull":        "YES" if macd_bull else "NO",
            "vol_ratio":        round(vol_ratio, 2),
            "avg_dv_m":         round(avg_dv / 1_000_000, 2),
            "perf_20d":         round(perf_20, 1),
            "perf_60d":         round(perf_60, 1),
            "perf_120d":        round(perf_120, 1),
            "base_range":       round(base_range, 1),
            "relax_level":      relax,
            "score":            round(score, 1),
            # Catalyst signals for visibility/Telegram
            "cat_pocket_pivot": catalysts["pocket_pivot_recent"],
            "cat_vol_climax":   catalysts["volume_climax"],
            "cat_gap_pct":      round(catalysts["up_gap_pct"], 2),
            "cat_vcp_strength": round(catalysts["vcp_strength"], 2),
            "cat_earnings_blackout": (catalyst_signals or {}).get("earnings_in_blackout", False),
            "cat_earnings_beat": (catalyst_signals or {}).get("earnings_beat_recent", False),
            "cat_earnings_next_days": (catalyst_signals or {}).get("earnings_next_days"),
            "cat_short_pct":    (catalyst_signals or {}).get("short_pct_float"),
            "cat_analyst_upside": (catalyst_signals or {}).get("analyst_target_upside"),
        }

    except Exception as e:
        debug["processing_error"] += 1
        return None


# =============================================================
# SECTOR
# =============================================================
def load_sector_cache():
    try:
        with open(SECTOR_CACHE, "r", encoding="utf-8") as f:
            d = json.load(f)
            return d if isinstance(d, dict) else {}
    except Exception:
        return {}


def save_sector_cache(cache):
    try:
        with open(SECTOR_CACHE, "w", encoding="utf-8") as f:
            json.dump(cache, f, ensure_ascii=False, indent=2)
    except Exception:
        pass


def enrich_sector(candidates):
    if not candidates:
        return candidates
    cache = load_sector_cache()
    for row in candidates:
        t = row["ticker"]
        if t not in cache:
            try:
                with suppress_output():
                    info = yf.Ticker(t).info
                cache[t] = info.get("sector", "Unknown") if isinstance(info, dict) else "Unknown"
            except Exception:
                cache[t] = "Unknown"
        row["sector"] = cache[t]
    save_sector_cache(cache)
    df = pd.DataFrame(candidates).sort_values(
        ["score", "rr", "vol_ratio"], ascending=False
    ).reset_index(drop=True)
    return df.to_dict("records")


# =============================================================
# SCAN PIPELINE WITH ADAPTIVE FALLBACK
# =============================================================
def run_scan(tickers, market_regime):
    """
    Three-pass adaptive scan:
      Pass 0 – strict filters
      Pass 1 – relaxed filters   (if pass 0 < MIN_SIGNALS)
      Pass 2 – broad sweep       (if pass 1 < MIN_SIGNALS)
    Returns list of candidates (best pass used).
    """
    all_frames = {}
    debug = Counter()

    batches = list(chunked(tickers, BATCH_SIZE))
    for batch in tqdm(batches, desc="Downloading"):
        raw = None
        try:
            with suppress_output():
                raw = yf.download(
                    tickers=" ".join(batch),
                    period=HISTORY_PERIOD,
                    auto_adjust=True,
                    progress=False,
                    threads=True,
                    group_by="ticker",
                )
        except Exception:
            pass

        for ticker in batch:
            frame = extract_ticker_frame(raw, ticker)
            if frame is not None:
                all_frames[ticker] = frame

    print(f"  Usable frames: {len(all_frames)} / {len(tickers)}")

    sector_cache = load_sector_cache()

    for relax in range(3):
        candidates = []
        pass_debug = Counter()
        for ticker, frame in all_frames.items():
            result = scan_ticker(ticker, frame, market_regime, pass_debug, sector_cache, relax=relax)
            if result is not None:
                candidates.append(result)

        debug += pass_debug

        if len(candidates) >= MIN_SIGNALS:
            if relax > 0:
                print(f"  Note: filters relaxed to level {relax} to find signals.")
            break
        else:
            print(f"  Pass {relax}: {len(candidates)} signals – relaxing filters...")

    # Deduplicate tickers
    seen, unique = set(), []
    for c in sorted(candidates, key=lambda x: x["score"], reverse=True):
        if c["ticker"] not in seen:
            seen.add(c["ticker"])
            unique.append(c)

    return unique[:MAX_SIGNALS], debug


def apply_sector_cap(candidates):
    """Sector diversification applied after enrich_sector() has set real sector values."""
    sector_count = {}
    diversified  = []
    for c in candidates:
        sector = c.get("sector", "Unknown")
        setup  = c.get("setup", "")
        limit  = 3 if setup == "REVERSAL" else 2
        if sector_count.get(sector, 0) < limit:
            sector_count[sector] = sector_count.get(sector, 0) + 1
            diversified.append(c)
    return diversified


# =============================================================
# DISPLAY
# =============================================================
def print_signals(candidates):
    if not candidates:
        print("\nNo trade setups found today.")
        return

    print(f"\n{'='*72}")
    print(f"  TOP TRADE SIGNALS  ({len(candidates)} found)")
    print(f"{'='*72}")

    for i, row in enumerate(candidates[:TOP_RESULTS], 1):
        rl = row.get("relax_level", 0)
        rl_str = "" if rl == 0 else f"  [filter-relax={rl}]"
        print(f"\n{i}. {row['ticker']}  |  {row['setup']}  |  {row.get('sector','?')}  |  Score: {row['score']}{rl_str}")
        print(f"   Action     : {row['action']}")
        print(f"   Price now  : {row['price']}   Buy above: {row['buy_above']}   Stop: {row['stop']}   Target: {row['target']}")
        print(f"   Upside: {row['upside_pct']}%   Risk: {row['risk_pct']}%   RR: {row['rr']}   Horizon: {row['horizon']}")
        print(f"   RSI: {row['rsi']}   MACD bull: {row['macd_bull']}   Vol ratio: {row['vol_ratio']}   AvgDV: ${row['avg_dv_m']}M")
        print(f"   Perf 20d: {row['perf_20d']}%   60d: {row['perf_60d']}%   120d: {row['perf_120d']}%   Base range: {row['base_range']}%")

    print(f"\n{'='*72}")
    print("Legend:")
    print("  BREAKOUT   = pressing/clearing 20d high now  -> buy on breakout")
    print("  REVERSAL   = oversold stock turning up       -> buy the dip")
    print("  RR         = reward/risk ratio (>1.5 good, >2.5 excellent)")
    print(f"{'='*72}\n")




# =============================================================
# COMPANY NAMES
# =============================================================
COMPANY_NAME_CACHE = "company_names.json"

def load_company_names():
    try:
        with open(COMPANY_NAME_CACHE, "r", encoding="utf-8") as f:
            return json.load(f)
    except FileNotFoundError:
        return {}

def save_company_names(cache):
    try:
        with open(COMPANY_NAME_CACHE, "w", encoding="utf-8") as f:
            json.dump(cache, f, indent=2, ensure_ascii=False)
    except Exception:
        pass

def get_company_name(ticker, cache):
    if ticker in cache:
        return cache[ticker]
    try:
        with suppress_output():
            info = yf.Ticker(ticker).info
        name = info.get("shortName") or info.get("longName") or ticker
        # Shorten common suffixes for cleaner display
        for suffix in [" Inc.", " Inc", " Corp.", " Corp", " Ltd.", " Ltd",
                       " Holdings", " Group", " Co.", " Co", " plc", " AG", " SE"]:
            if name.endswith(suffix):
                name = name[:-len(suffix)].strip()
                break
        cache[ticker] = name
    except Exception:
        cache[ticker] = ticker
    return cache[ticker]


# =============================================================
# TELEGRAM
# =============================================================
def send_telegram(text):
    """Send a message via Telegram Bot API."""
    if not TELEGRAM_ENABLED:
        return
    if not TELEGRAM_TOKEN or not TELEGRAM_CHAT_ID:
        print("Telegram: Token/Chat-ID not configured, skipping.")
        return
    try:
        import urllib.request
        url  = f"https://api.telegram.org/bot{TELEGRAM_TOKEN}/sendMessage"
        data = json.dumps({
            "chat_id":    TELEGRAM_CHAT_ID,
            "text":       text,
            "parse_mode": "HTML",
        }).encode("utf-8")
        req = urllib.request.Request(url, data=data,
              headers={"Content-Type": "application/json"})
        urllib.request.urlopen(req, timeout=10)
        print("Telegram: Message sent.")
    except Exception as e:
        print(f"Telegram error: {e}")


def escape_md(text):
    """Escape special chars for Telegram HTML mode."""
    text = str(text)
    text = text.replace("&", "&amp;")
    text = text.replace("<", "&lt;")
    text = text.replace(">", "&gt;")
    return text
def get_no_signal_message(market_regime):
    import random
    from datetime import datetime
    mode = market_regime.get("mode", "UNKNOWN")
    date_str = datetime.now().strftime("%d. %B %H:%M Uhr")

    msgs = [
        "Heute habe ich keine Signale für euch, mächtige Investoren. Der Markt schweigt.",
        "Kein Signal heute. Manchmal ist Nichtstun die beste Investition.",
        "Der Scanner hat gesprochen: heute bleibt das Pulver trocken.",
        "Keine Setups heute. Vielleicht ist das Universum der Meinung, ihr habt genug riskiert.",
        "Heute: null Signale. Euer Kontostand dankt es euch möglicherweise.",
        "Stille an der Front. Kein Trade ist auch eine Position.",
        "Heute schlafen die Breakouts. Morgen erwachen sie wieder.",
        "Der Markt flüstert heute nichts. Ich höre trotzdem zu.",
        "Keine Kandidaten heute. Qualität vor Quantität — das ist ApexScan-Philosophie.",
        "Ruhige Nacht an den Märkten. Genießt euren Schlaf, Investoren.",
        "Heute kein Signal. Manchmal ist der beste Trade der, den man nicht macht.",
        "Scanner läuft sauber — der Markt liefert heute einfach nichts Würdiges.",
        "Kein Ausbruch heute. Der Markt testet eure Geduld. Besteht den Test.",
        "Heute: Funkstille. Der nächste Breakout wartet bereits in den Startlöchern.",
        "Keine Signale. Die Aktien brauchen heute eine Pause. Ihr auch.",
        "ApexScan hat alles geprüft und für zu riskant befunden. Spart euer Geld.",
        "Nichts heute. Aber morgen? Vielleicht. Wahrscheinlich. Eventuell.",
        "Der Scanner ruht. Nicht weil er müde ist, sondern weil der Markt es verdient.",
    ]

    text = random.choice(msgs)
    summary = escape_md(market_regime.get("summary", ""))
    return (
        "\U0001f4a4 <b>ApexScan</b> · " + date_str + "\n\n"
        + escape_md(text) + "\n\n"
        + "<i>" + summary + "</i>"
    )

def build_telegram_message(candidates, market_regime):
    from datetime import datetime
    now      = datetime.now()
    date_str = escape_md(now.strftime("%d. %B · %H:%M"))
    mode     = escape_md(market_regime.get("mode", "UNKNOWN"))
    icon     = "\U0001f7e2" if market_regime.get("risk_on") else "\U0001f534"
    NL       = "\n"
    name_cache = load_company_names()

    # Group by setup, preserve score order
    groups = {"BREAKOUT": [], "POSITION": [], "PRE-ROCKET": [], "REVERSAL": []}
    for c in candidates:
        key = c.get("setup", "")
        if key in groups:
            groups[key].append(c)

    setup_cfg = [
        ("BREAKOUT",   "\U0001f535", "Breakout"),
        ("POSITION",   "\U0001f7e3", "Position"),
        ("PRE-ROCKET", "\U0001f7e1", "Pre-Rocket"),
        ("REVERSAL",   "\U0001f7e2", "Reversal"),
    ]

    lines = [icon + " <b>ApexScan · " + date_str + " · " + mode + "</b>"]

    for key, sicon, label in setup_cfg:
        items = groups[key]
        if not items:
            continue

        # Setup header
        lines.append("\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500")
        lines.append(sicon + " <b>" + label + "</b>")

        for c in items:
            name    = get_company_name(c["ticker"], name_cache)
            ticker  = escape_md(c["ticker"])
            cname   = escape_md(name)
            price   = escape_md(str(c["price"]))
            target  = escape_md(str(c["target"]))
            upside  = escape_md(str(c["upside_pct"]))
            rr      = escape_md(str(c["rr"]))
            horizon = escape_md(c["horizon"].replace("weeks","Wo.").replace("week","Wo."))
            buy     = escape_md(str(c["buy_above"]))
            stop    = escape_md(str(c["stop"]))
            rsi     = escape_md(str(c["rsi"]))
            score   = escape_md(str(c["score"]))

            lines.append("\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500")
            lines.append("<b>" + ticker + " · " + cname + "</b>")
            lines.append("$" + price + " \u2192 $" + target + "  \u2b06 <b>+" + upside + "%</b>")
            lines.append("RR " + rr + "  ·  Entry $" + buy + "  ·  Stop $" + stop)
            lines.append("RSI " + rsi + "  ·  " + horizon + "  ·  Score " + score)

    lines.append("\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500")
    save_company_names(name_cache)
    return NL.join(lines)


# =============================================================
# SIGNAL EXPORT
# =============================================================
def save_signals(candidates):
    """Appends new signals to apex_signals.json (no duplicates)."""
    from datetime import datetime
    today = datetime.now().strftime("%Y-%m-%d")
    signals_file = "apex_signals.json"
    try:
        with open(signals_file, "r", encoding="utf-8") as f:
            existing = json.load(f)
    except FileNotFoundError:
        existing = []

    # Block same ticker if seen in last DUPLICATE_WINDOW_DAYS days
    today_dt = datetime.strptime(today, "%Y-%m-%d")
    recent_tickers = {
        r["ticker"] for r in existing
        if abs((today_dt - datetime.strptime(r["date"], "%Y-%m-%d")).days) <= DUPLICATE_WINDOW_DAYS
    }

    existing_keys = {(r["date"], r["ticker"]) for r in existing}
    new_entries = []
    skipped_recent = []
    for c in candidates:
        if (today, c["ticker"]) in existing_keys:
            continue
        if c["ticker"] in recent_tickers:
            skipped_recent.append(c["ticker"])
            continue
        entry = dict(c)
        entry["date"] = today
        new_entries.append(entry)

    if skipped_recent:
        print(f"  Skipped (seen in last 5 days): {', '.join(skipped_recent)}")

    existing.extend(new_entries)
    with open(signals_file, "w", encoding="utf-8") as f:
        json.dump(existing, f, indent=2, ensure_ascii=False)
    print(f"Signals saved: {len(new_entries)} new -> {signals_file}  (total: {len(existing)})")


# =============================================================
# MAIN
# =============================================================
def main():
    # Sync with GitHub before scan to avoid duplicate signals
    import subprocess, os
    if os.path.exists(".git"):
        try:
            subprocess.run(["git", "pull", "origin", "master"],
                           capture_output=True, check=True)
            print("Git: Synced with GitHub.")
        except subprocess.CalledProcessError:
            print("Git: Pull failed or no remote – continuing anyway.")

    # Load tickers from both markets
    us_tickers = clean_universe(load_tickers(US_TICKER_FILE))
    eu_tickers = clean_universe(load_tickers(EU_TICKER_FILE))
    all_tickers = unique_keep_order(us_tickers + eu_tickers)

    if not all_tickers:
        print("No tickers loaded. Check us_tickers.txt and eu_tickers.txt")
        return

    print(f"Tickers loaded: {len(us_tickers)} US  +  {len(eu_tickers)} EU  =  {len(all_tickers)} total")

    market_regime = get_market_regime()
    save_market_regime(market_regime)
    print(f"Market regime : {market_regime['summary']}\n")

    candidates, debug = run_scan(all_tickers, market_regime)

    print(f"\nCandidates before sector enrichment: {len(candidates)}")
    print("Debug summary:")
    for k, v in debug.most_common(12):
        print(f"  {k}: {v}")

    candidates = enrich_sector(candidates)
    candidates = apply_sector_cap(candidates)
    print_signals(candidates)

    # Filter out tickers seen in last DUPLICATE_WINDOW_DAYS days (before Telegram AND before save)
    from datetime import datetime as _dt
    today = _dt.now().strftime("%Y-%m-%d")
    today_dt = _dt.strptime(today, "%Y-%m-%d")
    try:
        with open("apex_signals.json", "r", encoding="utf-8") as f:
            _existing = json.load(f)
    except FileNotFoundError:
        _existing = []
    recent_tickers = {
        r["ticker"] for r in _existing
        if abs((today_dt - _dt.strptime(r["date"], "%Y-%m-%d")).days) <= DUPLICATE_WINDOW_DAYS
        and r.get("relax_level", 0) == 0
    }
    deduped = [c for c in candidates if c["ticker"] not in recent_tickers]
    skipped = [c["ticker"] for c in candidates if c["ticker"] in recent_tickers]
    if skipped:
        print(f"  Duplicate filter: {', '.join(skipped)} skipped (seen in last {DUPLICATE_WINDOW_DAYS} days).")
    candidates = deduped

    save_signals(candidates)

    # Send Telegram notification — eligibility → quality → top 2 by score
    if candidates:
        # Telegram eligibility:
        #   BREAKOUT: only from strict pass (relax=0) — relax=1 BREAKOUTs underperform
        #   REVERSAL: always eligible (is always relax=0 by construction)
        def tg_eligible(c):
            if c.get("setup") == "BREAKOUT":
                return c.get("relax_level", 0) == 0
            return True

        eligible = [c for c in candidates if tg_eligible(c)]
        n_filtered = len(candidates) - len(eligible)
        if n_filtered:
            print(f"  Telegram filter: {n_filtered} weak BREAKOUT(s) from relax=1 excluded.")

        # Apply quality filter on eligible pool (setup-specific score thresholds)
        def _min_score_for(c):
            return TG_MIN_SCORE.get(c.get("setup", ""), TG_MIN_SCORE_DEFAULT)

        quality = [c for c in eligible if
                   c.get("rr", 0)         >= TG_MIN_RR and
                   c.get("upside_pct", 0) >= TG_MIN_UPSIDE and
                   c.get("score", 0)      >= _min_score_for(c)]

        if not quality and eligible:
            # Fallback: best eligible even if below quality threshold
            quality = sorted(eligible, key=lambda x: x.get("score", 0), reverse=True)[:1]
            print("  Note: No signals passed quality filter — sending best eligible.")

        if quality:
            top2 = sorted(quality, key=lambda x: x.get("score", 0), reverse=True)[:2]
            msg = build_telegram_message(top2, market_regime)
            send_telegram(msg)
        else:
            # Alle Kandidaten rausgefiltert (z.B. nur relax=1 BREAKOUTs, keine REVERSALs)
            print("  Note: All candidates filtered out — sending no-signal message.")
            send_telegram(get_no_signal_message(market_regime))
    else:
        send_telegram(get_no_signal_message(market_regime))


if __name__ == "__main__":
    main()